export const vocabulary = [
  {
    vn: "ăn cắp, lấy trộm",
    pronounce: "[stiːl]",
    type: "v.",
    eng: "steal",
  },
  {
    vn: "thông minh",
    pronounce: "[smɑːrt]",
    type: "adj.",
    eng: "smart",
  },
  {
    vn: "bước đi, bước",
    pronounce: "[stɛp]",
    type: "n.",
    eng: "step",
  },
  {
    vn: "dạ dày, bụng",
    pronounce: "[ˈstʌmək]",
    type: "n.",
    eng: "stomach",
  },
  {
    vn: "hòn đá, viên đá",
    pronounce: "[stəʊn]",
    type: "n.",
    eng: "stone",
  },
  {
    vn: "cơn bão, bão",
    pronounce: "[stɔːm]",
    type: "n.",
    eng: "storm",
  },
  {
    vn: "thẳng, thẳng hàng",
    pronounce: "[streɪt]",
    type: "adv., adj.",
    eng: "straight",
  },
  {
    vn: "lạ lùng, kỳ quặc",
    pronounce: "[streɪndʒ]",
    type: "adj.",
    eng: "strange",
  },
  {
    vn: "chiến lược",
    pronounce: "[ˈstrætədʒi]",
    type: "n.",
    eng: "strategy",
  },
  {
    vn: "cấu trúc, kết cấu",
    pronounce: "[ˈstrʌk.tʃər]",
    type: "n.",
    eng: "structure",
  },
  {
    vn: "ngu ngốc, ngớ ngẩn",
    pronounce: "[ˈstjuːpɪd]",
    type: "adj.",
    eng: "stupid",
  },
  {
    vn: "thành công, hiệu quả",
    pronounce: "[səkˈsɛsfʊl]",
    type: "adj.",
    eng: "successful",
  },
  {
    vn: "như vậy, như thế",
    pronounce: "[sʌtʃ]",
    type: "det./pron.",
    eng: "such",
  },
  {
    vn: "đột ngột, bất ngờ",
    pronounce: "[ˈsʌdənli]",
    type: "adv.",
    eng: "suddenly",
  },
  {
    vn: "đề xuất, gợi ý",
    pronounce: "[səˈdʒɛst]",
    type: "v.",
    eng: "suggest",
  },
  {
    vn: "giả định, cho rằng",
    pronounce: "[səˈpəʊz]",
    type: "v.",
    eng: "suppose",
  },
  {
    vn: "sự ngạc nhiên, điều bất ngờ; làm ngạc nhiên, làm bất ngờ",
    pronounce: "[səˈpraɪz]",
    type: "n., v.",
    eng: "surprise",
  },
  {
    vn: "ngạc nhiên, bất ngờ",
    pronounce: "[səˈpraɪzd]",
    type: "adj.",
    eng: "surprised",
  },
  {
    vn: "ngạc nhiên, đáng ngạc nhiên",
    pronounce: "[səˈpraɪzɪŋ]",
    type: "adj.",
    eng: "surprising",
  },
  {
    vn: "cuộc khảo sát, cuộc điều tra",
    pronounce: "[ˈsɜːveɪ]",
    type: "n.",
    eng: "survey",
  },
  {
    vn: "ngọt ngào, dễ thương; món ngọt, đồ ngọt",
    pronounce: "[swiːt]",
    type: "adj., n.",
    eng: "sweet",
  },
  {
    vn: "biểu tượng, ký hiệu",
    pronounce: "[ˈsɪmbəl]",
    type: "n.",
    eng: "symbol",
  },
  {
    vn: "hệ thống, phương thức",
    pronounce: "[ˈsɪstəm]",
    type: "n.",
    eng: "system",
  },
  {
    vn: "máy tính bảng, viên thuốc",
    pronounce: "[ˈtæblət]",
    type: "n.",
    eng: "tablet",
  },
  {
    vn: "mục tiêu, mục đích",
    pronounce: "[ˈtɑːrɡɪt]",
    type: "n.",
    eng: "target",
  },
  {
    vn: "khẩu vị, vị; nếm, thưởng thức vị",
    pronounce: "[teɪst]",
    type: "n., v.",
    eng: "taste",
  },
  {
    vn: "sự dạy, việc dạy học",
    pronounce: "[ˈtiːtʃɪŋ]",
    type: "n.",
    eng: "teaching",
  },
  {
    vn: "công nghệ, kỹ thuật",
    pronounce: "[tekˈnɒlədʒi]",
    type: "n.",
    eng: "technology",
  },
  {
    vn: "tuổi teen, tuổi vị thành niên",
    pronounce: "[ˈtiːneɪdʒ]",
    type: "adj.",
    eng: "teenage",
  },
  {
    vn: "nhiệt độ, thời tiết",
    pronounce: "[ˈtempərətʃər]",
    type: "n.",
    eng: "temperature",
  },
  {
    vn: "học kỳ, kỳ hạn",
    pronounce: "[tɜːrm]",
    type: "n.",
    eng: "term",
  },
  {
    vn: "chính họ, bản thân họ",
    pronounce: "[ðəmˈsɛlvz]",
    type: "pron.",
    eng: "themselves",
  },
  {
    vn: "dày, đậm",
    pronounce: "[θɪk]",
    type: "adj.",
    eng: "thick",
  },
  {
    vn: "kẻ trộm, tên trộm",
    pronounce: "[θiːf]",
    type: "n.",
    eng: "thief",
  },
  {
    vn: "mảnh mai, mỏng",
    pronounce: "[θɪn]",
    type: "adj.",
    eng: "thin",
  },
  {
    vn: "tư duy, suy nghĩ",
    pronounce: "[ˈθɪŋkɪŋ]",
    type: "n.",
    eng: "thinking",
  },
  {
    vn: "suy nghĩ, ý nghĩ",
    pronounce: "[θɔːt]",
    type: "n.",
    eng: "thought",
  },
  {
    vn: "ném, vứt",
    pronounce: "[θrəʊ]",
    type: "v.",
    eng: "throw",
  },
  {
    vn: "ngăn nắp, gọn gàng; dọn dẹp, ngăn nắp",
    pronounce: "[ˈtaɪdi]",
    type: "adj., v.",
    eng: "tidy",
  },
  {
    vn: "buộc, cột; cà vạt, chiếc cà vạt",
    pronounce: "[taɪ]",
    type: "v., n.",
    eng: "tie",
  },
  {
    vn: "đầu, phần đầu; mẹo, lời khuyên",
    pronounce: "[tɪp]",
    type: "n.",
    eng: "tip",
  },
  {
    vn: "dụng cụ, công cụ",
    pronounce: "[tuːl]",
    type: "n.",
    eng: "tool",
  },
  {
    vn: "chạm, tiếp xúc",
    pronounce: "[tʌtʃ]",
    type: "v.",
    eng: "touch",
  },
  {
    vn: "chuyến du lịch, hành trình",
    pronounce: "[tʊər]",
    type: "n.",
    eng: "tour",
  },
  {
    vn: "du lịch, ngành du lịch",
    pronounce: "[ˈtʊərɪzəm]",
    type: "n.",
    eng: "tourism",
  },
  {
    vn: "về phía, hướng về",
    pronounce: "[təˈwɔːdz]",
    type: "prep.",
    eng: "towards",
  },
  {
    vn: "khăn tắm, khăn lau",
    pronounce: "[ˈtaʊəl]",
    type: "n.",
    eng: "towel",
  },
  {
    vn: "tháp, tòa tháp",
    pronounce: "[ˈtaʊər]",
    type: "n.",
    eng: "tower",
  },
  {
    vn: "đồ chơi, đồ chơi",
    pronounce: "[tɔɪ]",
    type: "n., adj.",
    eng: "toy",
  },
  {
    vn: "đường đua, dải đường",
    pronounce: "[træk]",
    type: "n.",
    eng: "track",
  },
  {
    vn: "truyền thống, phong tục",
    pronounce: "[trəˈdɪʃən]",
    type: "n.",
    eng: "tradition",
  },
  {
    vn: "truyền thống, cổ truyền",
    pronounce: "[trəˈdɪʃənl]",
    type: "adj.",
    eng: "traditional",
  },
  {
    vn: "huấn luyện viên, người đào tạo",
    pronounce: "[ˈtreɪnər]",
    type: "n.",
    eng: "trainer",
  },
  {
    vn: "sự đào tạo, huấn luyện",
    pronounce: "[ˈtreɪnɪŋ]",
    type: "n.",
    eng: "training",
  },
  {
    vn: "giao thông, vận chuyển",
    pronounce: "[ˈtrænspɔːt]",
    type: "n.",
    eng: "transport",
  },
  {
    vn: "người đi du lịch, người đi lại",
    pronounce: "[ˈtrævələr]",
    type: "n.",
    eng: "traveller",
  },
  {
    vn: "rắc rối, phiền phức",
    pronounce: "[ˈtrʌbl]",
    type: "n.",
    eng: "trouble",
  },
  {
    vn: "xe tải, xe bán tải",
    pronounce: "[trʌk]",
    type: "n.",
    eng: "truck",
  },
  {
    vn: "sinh đôi, đôi",
    pronounce: "[twɪn]",
    type: "n., adj.",
    eng: "twin",
  },
  {
    vn: "điển hình, tiêu biểu",
    pronounce: "[ˈtɪpɪkl]",
    type: "adj.",
    eng: "typical",
  },
  {
    vn: "dưới lòng đất, dưới lòng đất",
    pronounce: "[ˈʌndəˌɡraʊnd]",
    type: "adj., adv.",
    eng: "underground",
  },
  {
    vn: "sự hiểu biết, sự lý hiểu",
    pronounce: "[ˌʌndərˈstændɪŋ]",
    type: "n.",
    eng: "understanding",
  },
  {
    vn: "đồng phục, bộ quần áo",
    pronounce: "[ˈjuːnɪfɔːm]",
    type: "n.",
    eng: "uniform",
  },
  {
    vn: "đơn vị, đơn vị",
    pronounce: "[ˈjuːnɪt]",
    type: "n.",
    eng: "unit",
  },
  {
    vn: "thống nhất, liên minh",
    pronounce: "[juːˈnaɪtɪd]",
    type: "adj.",
    eng: "united",
  },
  {
    vn: "bất thường, lạ lùng",
    pronounce: "[ʌnˈjuːʒuəl]",
    type: "adj.",
    eng: "unusual",
  },
  {
    vn: "đã từng, đã quen",
    pronounce: "[juːst tuː]",
    type: "modal v.",
    eng: "used to",
  },
  {
    vn: "thông thường, thường",
    pronounce: "[ˈjuːʒuəl]",
    type: "adj.",
    eng: "usual",
  },
  {
    vn: "thung lũng, hẻm núi",
    pronounce: "[ˈvæli]",
    type: "n.",
    eng: "valley",
  },
  {
    vn: "xe tải nhỏ, xe chở hàng",
    pronounce: "[væn]",
    type: "n.",
    eng: "van",
  },
  {
    vn: "sự đa dạng, loại hình",
    pronounce: "[vəˈraɪəti]",
    type: "n.",
    eng: "variety",
  },
  {
    vn: "phương tiện, xe cộ",
    pronounce: "[ˈviːɪkl]",
    type: "n.",
    eng: "vehicle",
  },
  {
    vn: "quan điểm, quan điểm, Cảnh vật, quang cảnh",
    pronounce: "[vjuː]",
    type: "n.",
    eng: "view",
  },
  {
    vn: "giọng nói, tiếng nói",
    pronounce: "[vɔɪs]",
    type: "n.",
    eng: "voice",
  },
  {
    vn: "chiến tranh, cuộc chiến",
    pronounce: "[wɔːr]",
    type: "n.",
    eng: "war",
  },
  {
    vn: "sóng, làn sóng",
    pronounce: "[weɪv]",
    type: "n.",
    eng: "wave",
  },
  {
    vn: "yếu đuối, yếu ớt",
    pronounce: "[wiːk]",
    type: "adj.",
    eng: "weak",
  },
  {
    vn: "ướt, ẩm ướt",
    pronounce: "[wɛt]",
    type: "adj.",
    eng: "wet",
  },
  {
    vn: "bánh xe",
    pronounce: "[wiːl]",
    type: "n.",
    eng: "wheel",
  },
  {
    vn: "trong khi, trong lúc",
    pronounce: "[waɪl]",
    type: "conj.",
    eng: "while",
  },
  {
    vn: "toàn bộ, tất cả",
    pronounce: "[həʊl]",
    type: "adj.",
    eng: "whole",
  },
  {
    vn: "của ai, của ai",
    pronounce: "[huːz]",
    type: "det./pron.",
    eng: "whose",
  },
  {
    vn: "rộng, rộng lớn",
    pronounce: "[waɪd]",
    type: "adj.",
    eng: "wide",
  },
  {
    vn: "hoang dã",
    pronounce: "[waɪld]",
    type: "adj.",
    eng: "wild",
  },
  {
    vn: "gió, cơn gió",
    pronounce: "[wɪnd]",
    type: "n.",
    eng: "wind",
  },
  {
    vn: "người chiến thắng, người thắng cuộc",
    pronounce: "[ˈwɪnər]",
    type: "n.",
    eng: "winner",
  },
  {
    vn: "mong muốn, ước muốn",
    pronounce: "[wɪʃ]",
    type: "v., n.",
    eng: "wish",
  },
  {
    vn: "gỗ, lâm sản",
    pronounce: "[wʊd]",
    type: "n.",
    eng: "wood",
  },
  {
    vn: "làm bằng gỗ, gỗ",
    pronounce: "[ˈwʊdən]",
    type: "adj.",
    eng: "wooden",
  },
  {
    vn: "đang làm việc, hoạt động",
    pronounce: "[ˈwɜːrkɪŋ]",
    type: "adj.",
    eng: "working",
  },
  {
    vn: "lo lắng, quan tâm",
    pronounce: "[ˈwʌri]",
    type: "v.",
    eng: "worry",
  },
  {
    vn: "vẫn chưa, đã, nhưng mà hay tuy nhiên trong câu đối lập",
    pronounce: "[jɛt]",
    type: "adv.",
    eng: "yet",
  },
  {
    vn: "tăng lên, mọc lên",
    pronounce: "[raɪz]",
    type: "v.",
    eng: "rise",
  },
  {
    vn: "đá, hòn đá",
    pronounce: "[rɒk]",
    type: "n.",
    eng: "rock (stone)",
  },
  {
    vn: "vai trò, vai diễn",
    pronounce: "[rəʊl]",
    type: "n.",
    eng: "role",
  },
  {
    vn: "mái nhà, nóc nhà",
    pronounce: "[ruːf]",
    type: "n.",
    eng: "roof",
  },
  {
    vn: "tròn, vòng quanh, xung quanh",
    pronounce: "[raʊnd]",
    type: "adj., adv., prep.",
    eng: "round",
  },
  {
    vn: "tuyến đường, lộ trình",
    pronounce: "[ruːt]",
    type: "n.",
    eng: "route",
  },
  {
    vn: "rác, vật bỏ đi",
    pronounce: "[ˈrʌbɪʃ]",
    type: "n.",
    eng: "rubbish",
  },
  {
    vn: "thô lỗ, bất lịch sự",
    pronounce: "[ruːd]",
    type: "adj.",
    eng: "rude",
  },
  {
    vn: "nước sốt, sốt",
    pronounce: "[sɔːs]",
    type: "n.",
    eng: "sauce",
  },
  {
    vn: "sợ hãi, hoảng sợ",
    pronounce: "[skɛəd]",
    type: "adj.",
    eng: "scared",
  },
  {
    vn: "đáng sợ, rùng rợn",
    pronounce: "[ˈskɛri]",
    type: "adj.",
    eng: "scary",
  },
  {
    vn: "cảnh, phân cảnh",
    pronounce: "[siːn]",
    type: "n.",
    eng: "scene",
  },
  {
    vn: "lịch trình, thời gian biểu",
    pronounce: "[/ˈskedʒ.uːl]",
    type: "n.",
    eng: "schedule",
  },
  {
    vn: "ghi điểm, điểm số; số điểm, kết quả",
    pronounce: "[skɔː]",
    type: "v., n.",
    eng: "score",
  },
  {
    vn: "màn hình, màn hình",
    pronounce: "[skriːn]",
    type: "n.",
    eng: "screen",
  },
  {
    vn: "mùa, mùa vụ",
    pronounce: "[ˈsiːzn]",
    type: "n.",
    eng: "season",
  },
  {
    vn: "ghế, chỗ ngồi",
    pronounce: "[siːt]",
    type: "n.",
    eng: "seat",
  },
  {
    vn: "bí mật, bí ẩn; bí mật, điều bí mật",
    pronounce: "[ˈsiːkrɪt]",
    type: "adj., n.",
    eng: "secret",
  },
  {
    vn: "thư ký, bí thư",
    pronounce: "[/ˈsek.rə.ter.i]",
    type: "n.",
    eng: "secretary",
  },
  {
    vn: "dường như, có vẻ như",
    pronounce: "[siːm]",
    type: "v.",
    eng: "seem",
  },
  {
    vn: "ý nghĩa, cảm giác",
    pronounce: "[sɛns]",
    type: "n.",
    eng: "sense",
  },
  {
    vn: "riêng biệt, tách rời",
    pronounce: "[ˈsɛpərət]",
    type: "adj.",
    eng: "separate",
  },
  {
    vn: "loạt, chuỗi",
    pronounce: "[ˈsɪəriːz]",
    type: "n.",
    eng: "series",
  },
  {
    vn: "nghiêm trọng, nghiêm túc",
    pronounce: "[ˈsɪəriəs]",
    type: "adj.",
    eng: "serious",
  },
  {
    vn: "phục vụ, phục vụ",
    pronounce: "[sɜːv]",
    type: "v.",
    eng: "serve",
  },
  {
    vn: "dịch vụ, sự phục vụ",
    pronounce: "[ˈsɜːvɪs]",
    type: "n.",
    eng: "service",
  },
  {
    vn: "một vài, một số",
    pronounce: "[ˈsɛvrəl]",
    type: "det./pron.",
    eng: "several",
  },
  {
    vn: "rung, lắc",
    pronounce: "[ʃeɪk]",
    type: "v.",
    eng: "shake",
  },
  {
    vn: "sẽ, sẽ phải",
    pronounce: "[ʃæl]",
    type: "modal v.",
    eng: "shall",
  },
  {
    vn: "hình dạng, hình dáng",
    pronounce: "[ʃeɪp]",
    type: "n.",
    eng: "shape",
  },
  {
    vn: "tờ, tấm",
    pronounce: "[ʃiːt]",
    type: "n.",
    eng: "sheet",
  },
  {
    vn: "tàu, con tàu",
    pronounce: "[ʃɪp]",
    type: "n.",
    eng: "ship",
  },
  {
    vn: "vai, phía vai",
    pronounce: "[ˈʃəʊldər]",
    type: "n.",
    eng: "shoulder",
  },
  {
    vn: "hét, la hét; tiếng hét, tiếng la",
    pronounce: "[ʃaʊt]",
    type: "v., n.",
    eng: "shout",
  },
  {
    vn: "đóng lại, khép lại; đóng cửa, khép cửa",
    pronounce: "[ʃʌt]",
    type: "v., adj.",
    eng: "shut",
  },
  {
    vn: "bên, phía bên",
    pronounce: "[saɪd]",
    type: "n.",
    eng: "side",
  },
  {
    vn: "dấu hiệu, biểu hiện; ký tên, đánh dấu",
    pronounce: "[saɪn]",
    type: "n., v.",
    eng: "sign",
  },
  {
    vn: "bạc, màu bạc",
    pronounce: "[ˈsɪlvər]",
    type: "n., adj.",
    eng: "silver",
  },
  {
    vn: "đơn giản, dễ dàng",
    pronounce: "[ˈsɪmpl]",
    type: "adj.",
    eng: "simple",
  },
  {
    vn: "từ khi, kể từ khi; bởi vì",
    pronounce: "[sɪns]",
    type: "prep., conj.",
    eng: "since",
  },
  {
    vn: "ông, thưa ông",
    pronounce: "[sɜːr]",
    type: "n.",
    eng: "sir",
  },
  {
    vn: "địa điểm, trang web",
    pronounce: "[saɪt]",
    type: "n.",
    eng: "site",
  },
  {
    vn: "trượt tuyết, trượt tuyết, ván trượt tuyết",
    pronounce: "[ski]",
    type: "v., adj., n.",
    eng: "ski",
  },
  {
    vn: "trượt tuyết, việc trượt tuyết",
    pronounce: "[ˈskiːɪŋ]",
    type: "n.",
    eng: "skiing",
  },
  {
    vn: "da, bì",
    pronounce: "[skɪn]",
    type: "n.",
    eng: "skin",
  },
  {
    vn: "bầu trời, không gian",
    pronounce: "[skaɪ]",
    type: "n.",
    eng: "sky",
  },
  {
    vn: "từ từ, chậm rãi",
    pronounce: "[ˈsləʊli]",
    type: "adv.",
    eng: "slowly",
  },
  {
    vn: "ngửi, mùi hương",
    pronounce: "[smɛl]",
    type: "v., n.",
    eng: "smell",
  },
  {
    vn: "khói, hơi khói; hút thuốc, làm bốc khói",
    pronounce: "[sməʊk]",
    type: "n., v.",
    eng: "smoke",
  },
  {
    vn: "việc hút thuốc, hút thuốc",
    pronounce: "[ˈsməʊkɪŋ]",
    type: "n.",
    eng: "smoking",
  },
  {
    vn: "xà phòng",
    pronounce: "[səʊp]",
    type: "n.",
    eng: "soap",
  },
  {
    vn: "xã hội, của xã hội",
    pronounce: "[ˈsəʊʃəl]",
    type: "adj.",
    eng: "social",
  },
  {
    vn: "xã hội, cộng đồng",
    pronounce: "[səˈsaɪəti]",
    type: "n.",
    eng: "society",
  },
  {
    vn: "tất, vớ",
    pronounce: "[sɒk]",
    type: "n.",
    eng: "sock",
  },
  {
    vn: "mềm, nhẹ",
    pronounce: "[sɒft]",
    type: "adj.",
    eng: "soft",
  },
  {
    vn: "binh sĩ, quân nhân",
    pronounce: "[ˈsəʊldʒər]",
    type: "n.",
    eng: "soldier",
  },
  {
    vn: "giải pháp, sự giải quyết",
    pronounce: "[səˈluːʃən]",
    type: "n.",
    eng: "solution",
  },
  {
    vn: "giải quyết, giải đố",
    pronounce: "[sɒlv]",
    type: "v.",
    eng: "solve",
  },
  {
    vn: "đâu đó, nơi nào đó",
    pronounce: "[ˈsʌmweə]",
    type: "adv., pron.",
    eng: "somewhere",
  },
  {
    vn: "loại, dạng",
    pronounce: "[sɔːt]",
    type: "n.",
    eng: "sort",
  },
  {
    vn: "nguồn, nguồn gốc",
    pronounce: "[sɔːs]",
    type: "n.",
    eng: "source",
  },
  {
    vn: "loa, người phát biểu",
    pronounce: "[ˈspiːkər]",
    type: "n.",
    eng: "speaker",
  },
  {
    vn: "cụ thể, riêng biệt",
    pronounce: "[spəˈsɪfɪk]",
    type: "adj.",
    eng: "specific",
  },
  {
    vn: "bài phát biểu, lời nói",
    pronounce: "[spiːtʃ]",
    type: "n.",
    eng: "speech",
  },
  {
    vn: "tốc độ, vận tốc",
    pronounce: "[spiːd]",
    type: "n.",
    eng: "speed",
  },
  {
    vn: "con nhện, nhện",
    pronounce: "[ˈspaɪdər]",
    type: "n.",
    eng: "spider",
  },
  {
    vn: "thìa, thìa dĩa",
    pronounce: "[spuːn]",
    type: "n.",
    eng: "spoon",
  },
  {
    vn: "vuông, hình vuông; quảng trường, hình vuông",
    pronounce: "[skweər]",
    type: "adj., n.",
    eng: "square",
  },
  {
    vn: "sân khấu, giai đoạn",
    pronounce: "[steɪdʒ]",
    type: "n.",
    eng: "stage",
  },
  {
    vn: "cầu thang, bậc thang",
    pronounce: "[steər]",
    type: "n.",
    eng: "stair",
  },
  {
    vn: "tem, con dấu",
    pronounce: "[stæmp]",
    type: "n.",
    eng: "stamp",
  },
  {
    vn: "tiểu bang, quốc gia",
    pronounce: "[steɪt]",
    type: "n.",
    eng: "state",
  },

  {
    vn: "máy in, máy in",
    pronounce: "/ˈprɪntə/",
    type: "n.",
    eng: "printer",
  },
  {
    vn: "nhà tù, tù nhân",
    pronounce: "/ˈprɪzn̩/",
    type: "n.",
    eng: "prison",
  },
  {
    vn: "giải thưởng, phần thưởng",
    pronounce: "/praɪz/",
    type: "n.",
    eng: "prize",
  },
  {
    vn: "quy trình, tiến trình",
    pronounce: "/ˈprəʊsɛs/",
    type: "n.",
    eng: "process",
  },
  {
    vn: "sản xuất, sản phẩm",
    pronounce: "/prəˈduːs/",
    type: "v.",
    eng: "produce",
  },
  {
    vn: "chuyên nghiệp, nghề nghiệp",
    pronounce: "/prəˈfɛʃənl̩/",
    type: "adj.",
    eng: "professional",
  },
  {
    vn: "giáo sư, giảng viên",
    pronounce: "/prəˈfɛsər/",
    type: "n.",
    eng: "professor",
  },
  {
    vn: "hồ sơ, hồ sơ",
    pronounce: "/ˈprəʊfaɪl/",
    type: "n.",
    eng: "profile",
  },
  {
    vn: "tiến triển, tiến độ",
    pronounce: "/ˈprəʊɡres/",
    type: "n.",
    eng: "progress",
  },
  {
    vn: "hứa, cam kết; lời hứa, sự cam kết",
    pronounce: "/ˈprɒmɪs/",
    type: "v., n.",
    eng: "promise",
  },
  {
    vn: "phát âm, gọi tên",
    pronounce: "/prəˈnaʊns/",
    type: "v.",
    eng: "pronounce",
  },
  {
    vn: "bảo vệ, bảo hộ",
    pronounce: "/prəˈtɛkt/",
    type: "v.",
    eng: "protect",
  },
  {
    vn: "cung cấp, cung ứng",
    pronounce: "/prəˈvaɪd/",
    type: "v.",
    eng: "provide",
  },
  {
    vn: "quán rượu, quán nhậu",
    pronounce: "/pʌb/",
    type: "n.",
    eng: "pub",
  },
  {
    vn: "công cộng, công cộng; công chúng, nhân dân",
    pronounce: "/ˈpʌblɪk/",
    type: "adj., n.",
    eng: "public",
  },
  {
    vn: "xuất bản, công bố",
    pronounce: "/ˈpʌblɪʃ/",
    type: "v.",
    eng: "publish",
  },
  {
    vn: "kéo, lôi",
    pronounce: "/pʊl/",
    type: "v.",
    eng: "pull",
  },
  {
    vn: "mục đích, ý định",
    pronounce: "/ˈpɜːpəs/",
    type: "n.",
    eng: "purpose",
  },
  {
    vn: "đẩy, chèo",
    pronounce: "/pʊʃ/",
    type: "v.",
    eng: "push",
  },
  {
    vn: "chất lượng, phẩm chất",
    pronounce: "/ˈkwɒlɪti/",
    type: "n.",
    eng: "quality",
  },
  {
    vn: "nữ hoàng, hoàng hậu",
    pronounce: "/kwiːn/",
    type: "n.",
    eng: "queen",
  },
  {
    vn: "một cách yên lặng, một cách im lặng",
    pronounce: "/ˈkwaɪətli/",
    type: "adv.",
    eng: "quietly",
  },
  {
    vn: "cuộc đua, đua; chủng tộc, dòng họ",
    pronounce: "/reɪs/",
    type: "n., v.",
    eng: "race",
  },
  {
    vn: "đường sắt, đường ray",
    pronounce: "/ˈreɪlweɪ/",
    type: "n.",
    eng: "railway",
  },
  {
    vn: "nâng cao, nâng lên",
    pronounce: "/reɪz/",
    type: "v.",
    eng: "raise",
  },
  {
    vn: "tỷ lệ, mức độ",
    pronounce: "/reɪt/",
    type: "n.",
    eng: "rate",
  },
  {
    vn: "hơn, thà; khá là, tương đối",
    pronounce: "/ˈrɑːðər/",
    type: "adv.",
    eng: "rather",
  },
  {
    vn: "đạt được, đến được",
    pronounce: "/riːtʃ/",
    type: "v.",
    eng: "reach",
  },
  {
    vn: "phản ứng, phản hồi",
    pronounce: "/riˈækt/",
    type: "v.",
    eng: "react",
  },
  {
    vn: "nhận ra, nhận thức",
    pronounce: "/ˈrɪəlaɪz/",
    type: "v.",
    eng: "realize",
  },
  {
    vn: "nhận, được",
    pronounce: "/rɪˈsiːv/",
    type: "v.",
    eng: "receive",
  },
  {
    vn: "gần đây, mới đây",
    pronounce: "/ˈriːsntli/",
    type: "adv.",
    eng: "recently",
  },
  {
    vn: "tiếp đón, lễ tiếp",
    pronounce: "/rɪˈsɛpʃn̩/",
    type: "n.",
    eng: "reception",
  },
  {
    vn: "công thức, công thức nấu ăn",
    pronounce: "/ˈrɛsɪpi/",
    type: "n.",
    eng: "recipe",
  },
  {
    vn: "nhận ra, nhận diện",
    pronounce: "/ˈrɛkəɡnaɪz/",
    type: "v.",
    eng: "recognize",
  },
  {
    vn: "khuyên, giới thiệu",
    pronounce: "/ˌrɛkəˈmɛnd/",
    type: "v.",
    eng: "recommend",
  },
  {
    vn: "hồ sơ, kỷ lục; ghi âm, ghi lại",
    pronounce: "/ˈrɛkɔːd/",
    type: "n., v.",
    eng: "record",
  },
  {
    vn: "bản ghi, bản ghi",
    pronounce: "/rɪˈkɔːdɪŋ/",
    type: "n.",
    eng: "recording",
  },
  {
    vn: "tái chế, phục hồi",
    pronounce: "/riːˈsaɪkl/",
    type: "v.",
    eng: "recycle",
  },
  {
    vn: "sự nghỉ ngơi, sự thư giãn; nghỉ ngơi, thư giãn",
    pronounce: "/rɛst/",
    type: "n., v.",
    eng: "rest",
  },
  {
    vn: "đánh giá, xem xét; bài đánh giá, bài phê bình",
    pronounce: "/rɪˈvjuː/",
    type: "n., v.",
    eng: "review",
  },
  {
    vn: "vấn đề, sự vật; quan trọng, có ý nghĩa",
    pronounce: "/ˈmætər/",
    type: "n., v.",
    eng: "matter",
  },
  {
    vn: "có thể",
    pronounce: "/meɪ/",
    type: "modal v.",
    eng: "may",
  },
  {
    vn: "phương tiện truyền thông",
    pronounce: "/ˈmiːdiə/",
    type: "n.",
    eng: "media",
  },
  {
    vn: "y khoa, thuộc y học",
    pronounce: "/ˈmɛdɪkl̩/",
    type: "adj.",
    eng: "medical",
  },
  {
    vn: "thuốc, y học",
    pronounce: "/ˈmɛdɪsɪn/",
    type: "n.",
    eng: "medicine",
  },
  {
    vn: "trí nhớ, ký ức",
    pronounce: "/ˈmɛməri/",
    type: "n.",
    eng: "memory",
  },
  {
    vn: "đề cập, nhắc đến",
    pronounce: "/ˈmɛnʃən/",
    type: "v.",
    eng: "mention",
  },
  {
    vn: "kim loại",
    pronounce: "/ˈmɛtəl/",
    type: "n.",
    eng: "metal",
  },
  {
    vn: "phương pháp, cách thức",
    pronounce: "/ˈmɛθəd/",
    type: "n.",
    eng: "method",
  },
  {
    vn: "giữa; ở giữa",
    pronounce: "/ˈmɪdl̩/",
    type: "n., adj.",
    eng: "middle",
  },
  {
    vn: "có thể",
    pronounce: "/maɪt/",
    type: "modal v.",
    eng: "might",
  },
  {
    vn: "tâm trí, ý kiến; quan tâm, để ý",
    pronounce: "/maɪnd/",
    type: "n., v.",
    eng: "mind",
  },
  {
    vn: "của tôi",
    pronounce: "/maɪn/",
    type: "pron.",
    eng: "mine",
  },
  {
    vn: "gương",
    pronounce: "/ˈmɪrər/",
    type: "n.",
    eng: "mirror",
  },
  {
    vn: "mất tích, thiếu hụt",
    pronounce: "/ˈmɪsɪŋ/",
    type: "adj.",
    eng: "missing",
  },
  {
    vn: "mặt trăng",
    pronounce: "/muːn/",
    type: "n.",
    eng: "moon",
  },
  {
    vn: "chủ yếu, hầu hết",
    pronounce: "/ˈməʊstli/",
    type: "adv.",
    eng: "mostly",
  },
  {
    vn: "xe máy, xe mô tô",
    pronounce: "/ˈmaɪtəʊˌsɪkl̩/",
    type: "n.",
    eng: "motorcycle",
  },
  {
    vn: "sự di chuyển, sự chuyển động",
    pronounce: "/ˈmuːvmənt/",
    type: "n.",
    eng: "movement",
  },
  {
    vn: "âm nhạc, thuộc âm nhạc",
    pronounce: "/ˈmjuːzɪkl̩/",
    type: "adj.",
    eng: "musical",
  },
  {
    vn: "nhạc sĩ",
    pronounce: "/mjuˈzɪʃən/",
    type: "n.",
    eng: "musician",
  },
  {
    vn: "chính tôi",
    pronounce: "/maɪˈsɛlf/",
    type: "pron.",
    eng: "myself",
  },
  {
    vn: "hẹp",
    pronounce: "/ˈnærəʊ/",
    type: "adj.",
    eng: "narrow",
  },
  {
    vn: "quốc gia, dân tộc",
    pronounce: "/ˈnæʃənl̩/",
    type: "adj.",
    eng: "national",
  },
  {
    vn: "gần như, hầu như",
    pronounce: "/ˈnɪəli/",
    type: "adv.",
    eng: "nearly",
  },
  {
    vn: "cần thiết, không thể thiếu",
    pronounce: "/ˈnɛsəsəri/",
    type: "adj.",
    eng: "necessary",
  },
  {
    vn: "cổ",
    pronounce: "/nɛk/",
    type: "n.",
    eng: "neck",
  },
  {
    vn: "không một trong hai",
    pronounce: "/ˈnaɪðər/",
    type: "det./pron.",
    eng: "neither",
  },
  {
    vn: "lo lắng, căng thẳng",
    pronounce: "/ˈnɜːvəs/",
    type: "adj.",
    eng: "nervous",
  },
  {
    vn: "mạng lưới, hệ thống",
    pronounce: "/ˈnɛtwɜːk/",
    type: "n.",
    eng: "network",
  },
  {
    vn: "tiếng ồn, tiếng động",
    pronounce: "/nɔɪz/",
    type: "n.",
    eng: "noise",
  },
  {
    vn: "ồn ào, inh ỏi",
    pronounce: "/ˈnɔɪzi/",
    type: "adj.",
    eng: "noisy",
  },
  {
    vn: "không ai, không cái gì",
    pronounce: "/nʌn/",
    type: "pron.",
    eng: "none",
  },
  {
    vn: "bình thường, thông thường",
    pronounce: "/ˈnɔːməl/",
    type: "adj.",
    eng: "normal",
  },
  {
    vn: "bình thường, thông thường",
    pronounce: "/ˈnɔːməli/",
    type: "adv.",
    eng: "normally",
  },
  {
    vn: "chú ý, để ý; thông báo, lưu ý",
    pronounce: "/ˈnəʊtɪs/",
    type: "v., n.",
    eng: "notice",
  },
  {
    vn: "tiểu thuyết, truyện",
    pronounce: "/ˈnɒvəl/",
    type: "n.",
    eng: "novel",
  },
  {
    vn: "không nơi nào, đâu cũng không",
    pronounce: "/ˈnəʊweə/",
    type: "adv.",
    eng: "nowhere",
  },
  {
    vn: "hạt dẻ cười, ốc vít",
    pronounce: "/nʌt/",
    type: "n.",
    eng: "nut",
  },
  {
    vn: "đại dương, biển cả",
    pronounce: "/ˈəʊʃn̩/",
    type: "n.",
    eng: "ocean",
  },
  {
    vn: "đề nghị, đề xuất; sự đề nghị, sự đề xuất",
    pronounce: "/ˈɒfər/",
    type: "v., n.",
    eng: "offer",
  },
  {
    vn: "sĩ quan, cán bộ",
    pronounce: "/ˈɒfɪsər/",
    type: "n.",
    eng: "officer",
  },
  {
    vn: "dầu, dầu",
    pronounce: "/ɔɪl/",
    type: "n.",
    eng: "oil",
  },
  {
    vn: "lên, vào (bề mặt phẳng)",
    pronounce: "/ˈɒntuː/",
    type: "prep.",
    eng: "onto",
  },
  {
    vn: "cơ hội, dịp",
    pronounce: "/ˌɒpəˈtjuːnəti/",
    type: "n.",
    eng: "opportunity",
  },
  {
    vn: "lựa chọn, sự chọn lựa",
    pronounce: "/ˈɒpʃən/",
    type: "n.",
    eng: "option",
  },
  {
    vn: "bình thường, thông thường",
    pronounce: "/ˈɔːdənri/",
    type: "adj.",
    eng: "ordinary",
  },
  {
    vn: "tổ chức, sự tổ chức",
    pronounce: "/ˌɔːɡənaɪˈzeɪʃən/",
    type: "n.",
    eng: "organization",
  },
  {
    vn: "tổ chức, sắp xếp",
    pronounce: "/ˈɔːɡənaɪz/",
    type: "v.",
    eng: "organize",
  },
  {
    vn: "nguyên bản, đầu tiên",
    pronounce: "/əˈrɪdʒənl/",
    type: "adj.",
    eng: "original",
  },
  {
    vn: "chúng tôi, bản thân chúng tôi",
    pronounce: "/aʊəˈsɛlvz/",
    type: "pron.",
    eng: "ourselves",
  },
  {
    vn: "lò nướng, lò vi sóng",
    pronounce: "/ˈʌvən/",
    type: "n.",
    eng: "oven",
  },
  {
    vn: "sở hữu, có",
    pronounce: "/əʊn/",
    type: "v.",
    eng: "own",
  },
  {
    vn: "chủ sở hữu, người sở hữu",
    pronounce: "/ˈəʊnər/",
    type: "n.",
    eng: "owner",
  },
  {
    vn: "đóng gói, gói",
    pronounce: "/pæk/",
    type: "v.",
    eng: "pack",
  },
  {
    vn: "đau đớn, nỗi đau",
    pronounce: "/peɪn/",
    type: "n.",
    eng: "pain",
  },
  {
    vn: "họa sĩ, người sơn",
    pronounce: "/ˈpeɪntər/",
    type: "n.",
    eng: "painter",
  },
  {
    vn: "cung điện, lâu đài",
    pronounce: "/ˈpælɪs/",
    type: "n.",
    eng: "palace",
  },
  {
    vn: "quần",
    pronounce: "/pænts/",
    type: "n.",
    eng: "pants",
  },
  {
    vn: "bãi đậu xe, chỗ đậu xe",
    pronounce: "/ˈpɑːkɪŋ/",
    type: "n.",
    eng: "parking",
  },
  {
    vn: "cụ thể, riêng biệt",
    pronounce: "/pəˈtɪkjʊlər/",
    type: "adj.",
    eng: "particular",
  },
  {
    vn: "qua, vượt qua",
    pronounce: "/pæs/",
    type: "v.",
    eng: "pass",
  },
  {
    vn: "hành khách, khách",
    pronounce: "/ˈpæsɪndʒər/",
    type: "n.",
    eng: "passenger",
  },
  {
    vn: "bệnh nhân, người bệnh",
    pronounce: "/ˈpeɪʃənt/",
    type: "n.",
    eng: "patient",
  },
  {
    vn: "mẫu, hình mẫu",
    pronounce: "/ˈpætərn/",
    type: "n.",
    eng: "pattern",
  },
  {
    vn: "tiền lương, tiền công",
    pronounce: "/peɪ/",
    type: "n.",
    eng: "pay",
  },
  {
    vn: "hòa bình, sự hoà bình",
    pronounce: "/piːs/",
    type: "n.",
    eng: "peace",
  },
  {
    vn: "xu, đồng xu",
    pronounce: "/ˈpeni/",
    type: "n.",
    eng: "penny",
  },
  {
    vn: "mỗi",
    pronounce: "/pəː/",
    type: "prep.",
    eng: "per",
  },
  {
    vn: "phần trăm",
    pronounce: "/pə sɛnt/",
    type: "n., adj./adv.",
    eng: "per cent",
  },
  {
    vn: "biểu diễn, thực hiện",
    pronounce: "/pəˈfɔːm/",
    type: "v.",
    eng: "perform",
  },
  {
    vn: "có lẽ, có thể",
    pronounce: "/pəˈhæps/",
    type: "adv.",
    eng: "perhaps",
  },
  {
    vn: "sự cho phép, quyền cho phép",
    pronounce: "/pəˈmɪʃn/",
    type: "n.",
    eng: "permission",
  },
  {
    vn: "tính cách, nhân cách",
    pronounce: "/ˌpɜːsəˈnæləti/",
    type: "n.",
    eng: "personality",
  },
  {
    vn: "xăng, nhiên liệu",
    pronounce: "/ˈpɛtrəl/",
    type: "n.",
    eng: "petrol",
  },
  {
    vn: "vật lý, cơ thể",
    pronounce: "/ˈfɪzɪkl̩/",
    type: "adj.",
    eng: "physical",
  },
  {
    vn: "vật lý học, môn vật lý",
    pronounce: "/ˈfɪzɪks/",
    type: "n.",
    eng: "physics",
  },
  {
    vn: "chọn, lựa chọn",
    pronounce: "/pɪk/",
    type: "v.",
    eng: "pick",
  },
  {
    vn: "phi công, người lái",
    pronounce: "/ˈpaɪlət/",
    type: "n.",
    eng: "pilot",
  },
  {
    vn: "hành tinh",
    pronounce: "/ˈplænɪt/",
    type: "n.",
    eng: "planet",
  },
  {
    vn: "nhựa, chất liệu nhựa",
    pronounce: "/ˈplæstɪk/",
    type: "n., adj.",
    eng: "plastic",
  },
  {
    vn: "đĩa",
    pronounce: "/pleɪt/",
    type: "n.",
    eng: "plate",
  },
  {
    vn: "bục, sân đỗ, nền",
    pronounce: "/ˈplætfɔːm/",
    type: "n.",
    eng: "platform",
  },
  {
    vn: "túi, túi quần",
    pronounce: "/ˈpɒkɪt/",
    type: "n.",
    eng: "pocket",
  },
  {
    vn: "lịch sự, lễ phép",
    pronounce: "/pəˈlaɪt/",
    type: "adj.",
    eng: "polite",
  },
  {
    vn: "ô nhiễm, ô nhiễm môi trường",
    pronounce: "/pəˈluːʃn̩/",
    type: "n.",
    eng: "pollution",
  },
  {
    vn: "dân số, dân số",
    pronounce: "/ˌpɒpjʊˈleɪʃn̩/",
    type: "n.",
    eng: "population",
  },
  {
    vn: "vị trí, tư thế",
    pronounce: "/pəˈzɪʃn/",
    type: "n.",
    eng: "position",
  },
  {
    vn: "sở hữu, vật sở hữu",
    pronounce: "/pəˈzɛʃn̩/",
    type: "n.",
    eng: "possession",
  },
  {
    vn: "khả năng, cơ hội",
    pronounce: "/ˌpɒsəˈbɪləti/",
    type: "n.",
    eng: "possibility",
  },
  {
    vn: "áp phích, áp phích",
    pronounce: "/ˈpəʊstər/",
    type: "n.",
    eng: "poster",
  },
  {
    vn: "sức mạnh, quyền lực",
    pronounce: "/ˈpaʊər/",
    type: "n.",
    eng: "power",
  },
  {
    vn: "dự đoán, tiên đoán",
    pronounce: "/prɪˈdɪkt/",
    type: "v.",
    eng: "predict",
  },
  {
    vn: "trình bày, đưa ra; hiện tại, bây giờ",
    pronounce: "/ˈprɛznt/",
    type: "v.",
    eng: "present",
  },
  {
    vn: "tổng thống, chủ tịch",
    pronounce: "/ˈprɛzɪdənt/",
    type: "n.",
    eng: "president",
  },
  {
    vn: "ngăn chặn, phòng chống",
    pronounce: "/prɪˈvɛnt/",
    type: "v.",
    eng: "prevent",
  },
  {
    vn: "in, in ấn",
    pronounce: "/prɪnt/",
    type: "v.",
    eng: "print",
  },

  {
    vn: "đầu gối",
    pronounce: "/niː/",
    type: "n.",
    eng: "knee",
  },
  {
    vn: "con dao",
    pronounce: "/naɪf/",
    type: "n.",
    eng: "knife",
  },
  {
    vn: "gõ, đập",
    pronounce: "/nɒk/",
    type: "v.",
    eng: "knock",
  },
  {
    vn: "kiến thức, hiểu biết",
    pronounce: "/ˈnɒlɪdʒ/",
    type: "n.",
    eng: "knowledge",
  },
  {
    vn: "phòng thí nghiệm",
    pronounce: "/læb/",
    type: "n.",
    eng: "lab",
  },
  {
    vn: "phụ nữ, bà mẹ",
    pronounce: "/ˈleɪdi/",
    type: "n.",
    eng: "lady",
  },
  {
    vn: "hồ, ao",
    pronounce: "/leɪk/",
    type: "n.",
    eng: "lake",
  },
  {
    vn: "đèn, đèn dầu",
    pronounce: "/læmp/",
    type: "n.",
    eng: "lamp",
  },
  {
    vn: "luật, pháp luật",
    pronounce: "/lɔː/",
    type: "n.",
    eng: "law",
  },
  {
    vn: "luật sư",
    pronounce: "/ˈlɔːjər/",
    type: "n.",
    eng: "lawyer",
  },
  {
    vn: "lười biếng",
    pronounce: "/ˈleɪzi/",
    type: "adj.",
    eng: "lazy",
  },
  {
    vn: "dẫn dắt, lãnh đạo",
    pronounce: "/liːd/",
    type: "v.",
    eng: "lead",
  },
  {
    vn: "lãnh đạo, người đứng đầu",
    pronounce: "/ˈliːdər/",
    type: "n.",
    eng: "leader",
  },
  {
    vn: "học tập, sự học hỏi",
    pronounce: "/ˈlɜːrnɪŋ/",
    type: "n.",
    eng: "learning",
  },
  {
    vn: "ít nhất",
    pronounce: "/liːst/",
    type: "det./pron., adv.",
    eng: "least",
  },
  {
    vn: "bài giảng, giảng dạy",
    pronounce: "/ˈlɛktʃər/",
    type: "n., v.",
    eng: "lecture",
  },
  {
    vn: "quả chanh",
    pronounce: "/ˈlɛmən/",
    type: "n.",
    eng: "lemon",
  },
  {
    vn: "cho mượn",
    pronounce: "/lɛnd/",
    type: "v.",
    eng: "lend",
  },
  {
    vn: "ít hơn",
    pronounce: "/lɛs/",
    type: "det./pron., adv.",
    eng: "less",
  },
  {
    vn: "lối sống",
    pronounce: "/ˈlaɪfstaɪl/",
    type: "n.",
    eng: "lifestyle",
  },
  {
    vn: "nâng lên; thang máy, cầu thang",
    pronounce: "/lɪft/",
    type: "v., n.",
    eng: "lift",
  },
  {
    vn: "có thể, có khả năng",
    pronounce: "/ˈlaɪkli/",
    type: "adj.",
    eng: "likely",
  },
  {
    vn: "người nghe",
    pronounce: "/ˈlɪsnər/",
    type: "n.",
    eng: "listener",
  },
  {
    vn: "khóa",
    pronounce: "/lɒk/",
    type: "v., n.",
    eng: "lock",
  },
  {
    vn: "xe tải",
    pronounce: "/ˈlɒri/",
    type: "n.",
    eng: "lorry",
  },
  {
    vn: "mất, lạc",
    pronounce: "/lɒst/",
    type: "adj.",
    eng: "lost",
  },
  {
    vn: "ồn ào, to; lớn tiếng",
    pronounce: "/laʊd/",
    type: "adj., adv.",
    eng: "loud",
  },
  {
    vn: "ồn ào, to",
    pronounce: "/ˈlaʊdli/",
    type: "adv.",
    eng: "loudly",
  },
  {
    vn: "đáng yêu, dễ thương",
    pronounce: "/ˈlʌvli/",
    type: "adj.",
    eng: "lovely",
  },
  {
    vn: "thấp",
    pronounce: "/ləʊ/",
    type: "adj., adv.",
    eng: "low",
  },
  {
    vn: "sự may mắn, vận may",
    pronounce: "/lʌk/",
    type: "n.",
    eng: "luck",
  },
  {
    vn: "may mắn, may mắn",
    pronounce: "/ˈlʌki/",
    type: "adj.",
    eng: "lucky",
  },
  {
    vn: "chính, chủ yếu",
    pronounce: "/ˈmeɪdʒər/",
    type: "adj.",
    eng: "major",
  },
  {
    vn: "quản lý, điều hành",
    pronounce: "/ˈmænɪdʒ/",
    type: "v.",
    eng: "manage",
  },
  {
    vn: "quản lý, người điều hành",
    pronounce: "/ˈmænɪdʒər/",
    type: "n.",
    eng: "manager",
  },
  {
    vn: "cách, thái độ, lối",
    pronounce: "/ˈmænər/",
    type: "n.",
    eng: "manner",
  },
  {
    vn: "đánh dấu; dấu vết, điểm số",
    pronounce: "/mɑːk/",
    type: "v., n.",
    eng: "mark",
  },
  {
    vn: "kết hôn, lấy chồng/ vợ",
    pronounce: "/ˈmæri/",
    type: "v.",
    eng: "marry",
  },
  {
    vn: "vật liệu, nguyên liệu",
    pronounce: "/məˈtɪəriəl/",
    type: "n.",
    eng: "material",
  },
  {
    vn: "toán học",
    pronounce: "/ˌmæθəˈmætɪks/",
    type: "n.",
    eng: "mathematics",
  },
  {
    vn: "môn toán",
    pronounce: "/mæθs/",
    type: "n.",
    eng: "maths",
  },

  {
    vn: "khoảng trống",
    pronounce: "/ɡæp/",
    type: "n.",
    eng: "gap",
  },
  {
    vn: "khí, ga",
    pronounce: "/ɡæs/",
    type: "n.",
    eng: "gas",
  },
  {
    vn: "cổng",
    pronounce: "/ɡeɪt/",
    type: "n.",
    eng: "gate",
  },
  {
    vn: "vàng",
    pronounce: "/ɡoʊld/",
    type: "n., adj.",
    eng: "gold",
  },
  {
    vn: "chính phủ",
    pronounce: "/ˈɡʌvərnmənt/",
    type: "n.",
    eng: "government",
  },
  {
    vn: "cỏ",
    pronounce: "/ɡræs/",
    type: "n.",
    eng: "grass",
  },
  {
    vn: "chào hỏi",
    pronounce: "/ɡriːt/",
    type: "v.",
    eng: "greet",
  },
  {
    vn: "mặt đất",
    pronounce: "/ɡraʊnd/",
    type: "n.",
    eng: "ground",
  },
  {
    vn: "khách mời",
    pronounce: "/ɡɛst/",
    type: "n.",
    eng: "guest",
  },
  {
    vn: "hướng dẫn; hướng dẫn viên",
    pronounce: "/ɡaɪd/",
    type: "n., v.",
    eng: "guide",
  },
  {
    vn: "súng",
    pronounce: "/ɡʌn/",
    type: "n.",
    eng: "gun",
  },
  {
    vn: "anh chàng, chàng trai",
    pronounce: "/ɡaɪ/",
    type: "n.",
    eng: "guy",
  },
  {
    vn: "thói quen",
    pronounce: "/ˈhæbɪt/",
    type: "n.",
    eng: "habit",
  },
  {
    vn: "hành lang, sảnh",
    pronounce: "/hɔːl/",
    type: "n.",
    eng: "hall",
  },
  {
    vn: "đau đầu",
    pronounce: "/ˈhɛdˌeɪk/",
    type: "n.",
    eng: "headache",
  },
  {
    vn: "trái tim",
    pronounce: "/hɑːrt/",
    type: "n.",
    eng: "heart",
  },
  {
    vn: "nhiệt độ; làm nóng",
    pronounce: "/hiːt/",
    type: "n., v.",
    eng: "heat",
  },
  {
    vn: "nặng",
    pronounce: "/ˈhɛvi/",
    type: "adj.",
    eng: "heavy",
  },
  {
    vn: "hữu ích",
    pronounce: "/ˈhɛlpfl̩/",
    type: "adj.",
    eng: "helpful",
  },
  {
    vn: "chính cô ấy",
    pronounce: "/hərˈsɛlf/",
    type: "pron.",
    eng: "herself",
  },
  {
    vn: "trốn",
    pronounce: "/haɪd/",
    type: "v.",
    eng: "hide",
  },
  {
    vn: "cao",
    pronounce: "/haɪ/",
    type: "adv.",
    eng: "high",
  },
  {
    vn: "đồi",
    pronounce: "/hɪl/",
    type: "n.",
    eng: "hill",
  },
  {
    vn: "chính anh ấy",
    pronounce: "/hɪmˈsɛlf/",
    type: "pron.",
    eng: "himself",
  },
  {
    vn: "đánh; va chạm",
    pronounce: "/hɪt/",
    type: "v., n.",
    eng: "hit",
  },
  {
    vn: "môn khúc côn cầu",
    pronounce: "/ˈhɒki/",
    type: "n.",
    eng: "hockey",
  },
  {
    vn: "giữ, nắm",
    pronounce: "/hoʊld/",
    type: "v.",
    eng: "hold",
  },
  {
    vn: "lỗ",
    pronounce: "/hoʊl/",
    type: "n.",
    eng: "hole",
  },
  {
    vn: "to lớn, khổng lồ",
    pronounce: "/hjuːdʒ/",
    type: "adj.",
    eng: "huge",
  },
  {
    vn: "con người, loài người",
    pronounce: "/ˈhjuːmən/",
    type: "adj., n.",
    eng: "human",
  },
  {
    vn: "làm đau; bị thương",
    pronounce: "/hɜːrt/",
    type: "v., adj.",
    eng: "hurt",
  },
  {
    vn: "nhận dạng",
    pronounce: "/aɪˈdɛntɪfaɪ/",
    type: "v.",
    eng: "identify",
  },
  {
    vn: "ốm, không khỏe",
    pronounce: "/ɪl/",
    type: "adj.",
    eng: "ill",
  },
  {
    vn: "bệnh tật, sự ốm đau",
    pronounce: "/ˈɪlnəs/",
    type: "n.",
    eng: "illness",
  },
  {
    vn: "ngay lập tức",
    pronounce: "/ɪˈmiːdiətli/",
    type: "adv.",
    eng: "immediately",
  },
  {
    vn: "không thể, không thực hiện được",
    pronounce: "/ɪmˈpɒsəbl̩/",
    type: "adj.",
    eng: "impossible",
  },
  {
    vn: "tăng, sự tăng",
    pronounce: "/ɪnˈkriːs/",
    type: "v., n.",
    eng: "increase",
  },
  {
    vn: "đáng kinh ngạc, không thể tin được",
    pronounce: "/ɪnˈkrɛdəbl̩/",
    type: "adj.",
    eng: "incredible",
  },
  {
    vn: "độc lập",
    pronounce: "/ˌɪndɪˈpɛndənt/",
    type: "adj.",
    eng: "independent",
  },
  {
    vn: "cá nhân; riêng biệt",
    pronounce: "/ˌɪndɪˈvɪdʒuəl/",
    type: "n., adj.",
    eng: "individual",
  },
  {
    vn: "ngành công nghiệp",
    pronounce: "/ˈɪndəstri/",
    type: "n.",
    eng: "industry",
  },
  {
    vn: "không chính thức, không trang trọng",
    pronounce: "/ɪnˈfɔːml̩/",
    type: "adj.",
    eng: "informal",
  },
  {
    vn: "vết thương, tổn thương",
    pronounce: "/ˈɪndʒəri/",
    type: "n.",
    eng: "injury",
  },
  {
    vn: "côn trùng",
    pronounce: "/ˈɪnsɛkt/",
    type: "n.",
    eng: "insect",
  },
  {
    vn: "bên trong",
    pronounce: "/ˈɪnsaɪd/",
    type: "prep., adv., n., adj.",
    eng: "inside",
  },
  {
    vn: "thay vì",
    pronounce: "/ɪnˈstɛd/",
    type: "adv.",
    eng: "instead",
  },
  {
    vn: "hướng dẫn",
    pronounce: "/ɪnˈstrʌkʃən/",
    type: "n.",
    eng: "instruction",
  },
  {
    vn: "người hướng dẫn, giảng viên",
    pronounce: "/ɪnˈstrʌktər/",
    type: "n.",
    eng: "instructor",
  },
  {
    vn: "công cụ, dụng cụ",
    pronounce: "/ˈɪnstrəmənt/",
    type: "n.",
    eng: "instrument",
  },
  {
    vn: "thông minh, sáng dạ",
    pronounce: "/ɪnˈtɛlɪdʒənt/",
    type: "adj.",
    eng: "intelligent",
  },
  {
    vn: "quốc tế",
    pronounce: "/ˌɪntərˈnæʃənl̩/",
    type: "adj.",
    eng: "international",
  },
  {
    vn: "sự giới thiệu, phần mở đầu",
    pronounce: "/ˌɪntrəˈdʌkʃən/",
    type: "n.",
    eng: "introduction",
  },
  {
    vn: "phát minh, sáng chế",
    pronounce: "/ɪnˈvɛnt/",
    type: "v.",
    eng: "invent",
  },
  {
    vn: "phát minh, sự sáng chế",
    pronounce: "/ɪnˈvɛnʃən/",
    type: "n.",
    eng: "invention",
  },
  {
    vn: "lời mời",
    pronounce: "/ˌɪnvɪˈteɪʃən/",
    type: "n.",
    eng: "invitation",
  },
  {
    vn: "mời, mời gọi",
    pronounce: "/ɪnˈvaɪt/",
    type: "v.",
    eng: "invite",
  },
  {
    vn: "liên quan, dính líu",
    pronounce: "/ɪnˈvɒlv/",
    type: "v.",
    eng: "involve",
  },
  {
    vn: "mục, món",
    pronounce: "/ˈaɪtəm/",
    type: "n.",
    eng: "item",
  },
  {
    vn: "chính nó",
    pronounce: "/ɪtˈsɛlf/",
    type: "pron.",
    eng: "itself",
  },
  {
    vn: "mứt, sự tắc nghẽn",
    pronounce: "/dʒæm/",
    type: "n.",
    eng: "jam",
  },
  {
    vn: "nhạc jazz",
    pronounce: "/dʒæz/",
    type: "n.",
    eng: "jazz",
  },
  {
    vn: "trang sức",
    pronounce: "/ˈdʒuːəlri/",
    type: "n.",
    eng: "jewellery",
  },
  {
    vn: "trò đùa; nói đùa",
    pronounce: "/dʒəʊk/",
    type: "n., v.",
    eng: "joke",
  },
  {
    vn: "nhà báo",
    pronounce: "/ˈdʒɜːrnəlɪst/",
    type: "n.",
    eng: "journalist",
  },
  {
    vn: "nhảy, sự nhảy",
    pronounce: "/dʒʌmp/",
    type: "v., n.",
    eng: "jump",
  },
  {
    vn: "trẻ con",
    pronounce: "/kɪd/",
    type: "n.",
    eng: "kid",
  },
  {
    vn: "vua",
    pronounce: "/kɪŋ/",
    type: "n.",
    eng: "king",
  },
  {
    vn: "khám phá",
    pronounce: "/dɪˈskʌvər/",
    type: "v.",
    eng: "discover",
  },
  {
    vn: "cuộc thảo luận",
    pronounce: "/dɪˈskʌʃən/",
    type: "n.",
    eng: "discussion",
  },
  {
    vn: "bệnh tật",
    pronounce: "/dɪˈziːz/",
    type: "n.",
    eng: "disease",
  },
  {
    vn: "khoảng cách",
    pronounce: "/ˈdɪstəns/",
    type: "n.",
    eng: "distance",
  },
  {
    vn: "đã ly dị",
    pronounce: "/dɪˈvɔːrst/",
    type: "adj.",
    eng: "divorced",
  },
  {
    vn: "tài liệu",
    pronounce: "/ˈdɒkjʊmənt/",
    type: "n.",
    eng: "document",
  },
  {
    vn: "kịch",
    pronounce: "/ˈdrɑːmə/",
    type: "n.",
    eng: "drama",
  },
  {
    vn: "bản vẽ",
    pronounce: "/ˈdrɔːɪŋ/",
    type: "n.",
    eng: "drawing",
  },
  {
    vn: "giấc mơ; mơ",
    pronounce: "/driːm/",
    type: "n., v.",
    eng: "dream",
  },
  {
    vn: "việc lái xe",
    pronounce: "/ˈdraɪvɪŋ/",
    type: "n.",
    eng: "driving",
  },
  {
    vn: "rơi",
    pronounce: "/drɒp/",
    type: "v.",
    eng: "drop",
  },
  {
    vn: "thuốc, ma túy",
    pronounce: "/drʌɡ/",
    type: "n.",
    eng: "drug",
  },
  {
    vn: "khô; làm khô",
    pronounce: "/draɪ/",
    type: "adj., v.",
    eng: "dry",
  },
  {
    vn: "kiếm được, thu được",
    pronounce: "/ɜːrn/",
    type: "v.",
    eng: "earn",
  },
  {
    vn: "trái đất",
    pronounce: "/ɜːrθ/",
    type: "n.",
    eng: "earth",
  },
  {
    vn: "dễ dàng",
    pronounce: "/ˈiːzɪli/",
    type: "adv.",
    eng: "easily",
  },
  {
    vn: "giáo dục",
    pronounce: "/ˌɛdʒʊˈkeɪʃən/",
    type: "n.",
    eng: "education",
  },
  {
    vn: "hiệu ứng",
    pronounce: "/ɪˈfɛkt/",
    type: "n.",
    eng: "effect",
  },
  {
    vn: "một trong hai; cũng vậy",
    pronounce: "/ˈaɪðər/",
    type: "det./pron., adv.",
    eng: "either",
  },
  {
    vn: "điện, điện tử",
    pronounce: "/ɪˈlɛktrɪk/",
    type: "adj.",
    eng: "electric",
  },
  {
    vn: "điện, điện tử",
    pronounce: "/ɪˈlɛktrɪkəl/",
    type: "adj.",
    eng: "electrical",
  },
  {
    vn: "điện, điện lực",
    pronounce: "/ɪˌlɛkˈtrɪsɪti/",
    type: "n.",
    eng: "electricity",
  },
  {
    vn: "điện tử",
    pronounce: "/ɪˌlɛkˈtrɒnɪk/",
    type: "adj.",
    eng: "electronic",
  },
  {
    vn: "thuê, sử dụng",
    pronounce: "/ɪmˈplɔɪ/",
    type: "v.",
    eng: "employ",
  },
  {
    vn: "nhân viên",
    pronounce: "/ɛmplɔɪˈiː/",
    type: "n.",
    eng: "employee",
  },
  {
    vn: "nhà tuyển dụng",
    pronounce: "/ɪmˈplɔɪər/",
    type: "n.",
    eng: "employer",
  },
  {
    vn: "trống rỗng",
    pronounce: "/ˈɛmpti/",
    type: "adj.",
    eng: "empty",
  },
  {
    vn: "năng lượng",
    pronounce: "/ˈɛnərdʒi/",
    type: "n.",
    eng: "energy",
  },
  {
    vn: "động cơ",
    pronounce: "/ˈɛndʒɪn/",
    type: "n.",
    eng: "engine",
  },
  {
    vn: "kỹ sư",
    pronounce: "/ˌɛndʒɪˈnɪr/",
    type: "n.",
    eng: "engineer",
  },
  {
    vn: "to lớn, khổng lồ",
    pronounce: "/ɪˈnɔːrməs/",
    type: "adj.",
    eng: "enormous",
  },
  {
    vn: "môi trường",
    pronounce: "/ɪnˈvaɪrənmənt/",
    type: "n.",
    eng: "environment",
  },
  {
    vn: "thiết bị",
    pronounce: "/ɪˈkwɪpmənt/",
    type: "n.",
    eng: "equipment",
  },
  {
    vn: "đặc biệt, nhất là",
    pronounce: "/ɪˈspɛʃəli/",
    type: "adv.",
    eng: "especially",
  },
  {
    vn: "bài luận",
    pronounce: "/ˈɛseɪ/",
    type: "n.",
    eng: "essay",
  },
  {
    vn: "hàng ngày",
    pronounce: "/ˈɛvridi/",
    type: "adj.",
    eng: "everyday",
  },
  {
    vn: "khắp mọi nơi",
    pronounce: "/ˈɛvrɪwɛr/",
    type: "adv.",
    eng: "everywhere",
  },
  {
    vn: "bằng chứng",
    pronounce: "/ˈɛvɪdəns/",
    type: "n.",
    eng: "evidence",
  },
  {
    vn: "chính xác, đúng đắn",
    pronounce: "/ɪɡˈzækt/",
    type: "adj.",
    eng: "exact",
  },
  {
    vn: "chính xác, đúng đắn",
    pronounce: "/ɪɡˈzæktli/",
    type: "adv.",
    eng: "exactly",
  },
  {
    vn: "xuất sắc, tuyệt vời",
    pronounce: "/ˈɛksələnt/",
    type: "adj.",
    eng: "excellent",
  },
  {
    vn: "trừ, ngoại trừ",
    pronounce: "/ɪkˈsɛpt/",
    type: "prep.",
    eng: "except",
  },
  {
    vn: "tồn tại",
    pronounce: "/ɪɡˈzɪst/",
    type: "v.",
    eng: "exist",
  },
  {
    vn: "mong đợi",
    pronounce: "/ɪkˈspɛkt/",
    type: "v.",
    eng: "expect",
  },
  {
    vn: "kinh nghiệm",
    pronounce: "/ɪkˈspɪriəns/",
    type: "n.",
    eng: "experience",
  },
  {
    vn: "thí nghiệm",
    pronounce: "/ɪkˈspɛrɪmənt/",
    type: "n.",
    eng: "experiment",
  },
  {
    vn: "chuyên gia, có chuyên môn",
    pronounce: "/ˈɛkspɜrt/",
    type: "n., adj.",
    eng: "expert",
  },
  {
    vn: "giải thích",
    pronounce: "/ˌɛkspləˈneɪʃən/",
    type: "n.",
    eng: "explanation",
  },
  {
    vn: "diễn đạt",
    pronounce: "/ɪkˈsprɛs/",
    type: "v.",
    eng: "express",
  },
  {
    vn: "sự diễn đạt",
    pronounce: "/ɪkˈsprɛʃən/",
    type: "n.",
    eng: "expression",
  },
  {
    vn: "cực đoan, cực kỳ",
    pronounce: "/ɪkˈstrim/",
    type: "adj.",
    eng: "extreme",
  },
  {
    vn: "cực kỳ, rất",
    pronounce: "/ɪkˈstrimli/",
    type: "adv.",
    eng: "extremely",
  },
  {
    vn: "yếu tố",
    pronounce: "/ˈfæktər/",
    type: "n.",
    eng: "factor",
  },
  {
    vn: "nhà máy",
    pronounce: "/ˈfæktəri/",
    type: "n.",
    eng: "factory",
  },
  {
    vn: "thất bại",
    pronounce: "/feɪl/",
    type: "v.",
    eng: "fail",
  },
  {
    vn: "công bằng, trung bình",
    pronounce: "/fɛr/",
    type: "adj.",
    eng: "fair",
  },
  {
    vn: "quạt",
    pronounce: "/fæn/",
    type: "n.",
    eng: "fan",
  },
  {
    vn: "nông nghiệp",
    pronounce: "/fɑːrm/",
    type: "v.",
    eng: "farm",
  },
  {
    vn: "nông nghiệp",
    pronounce: "/ˈfɑːrmɪŋ/",
    type: "n.",
    eng: "farming",
  },
  {
    vn: "thời trang",
    pronounce: "/ˈfæʃən/",
    type: "n.",
    eng: "fashion",
  },
  {
    vn: "mỡ, chất béo",
    pronounce: "/fæt/",
    type: "n.",
    eng: "fat",
  },
  {
    vn: "sự sợ hãi",
    pronounce: "/fɪər/",
    type: "n.",
    eng: "fear",
  },
  {
    vn: "đặc điểm, tính năng",
    pronounce: "/ˈfiːtʃər/",
    type: "n.",
    eng: "feature",
  },
  {
    vn: "cho ăn, nuôi",
    pronounce: "/fiːd/",
    type: "v.",
    eng: "feed",
  },
  {
    vn: "hư cấu, tưởng tượng",
    pronounce: "/ˈfɪkʃən/",
    type: "n.",
    eng: "fiction",
  },
  {
    vn: "lĩnh vực, cánh đồng",
    pronounce: "/fiːld/",
    type: "n.",
    eng: "field",
  },
  {
    vn: "chiến đấu, cuộc đấu",
    pronounce: "/faɪt/",
    type: "v., n.",
    eng: "fight",
  },
  {
    vn: "hình, con số",
    pronounce: "/ˈfɪɡjər/",
    type: "n.",
    eng: "figure",
  },
  {
    vn: "ngón tay",
    pronounce: "/ˈfɪŋɡər/",
    type: "n.",
    eng: "finger",
  },
  {
    vn: "trước hết",
    pronounce: "/ˈfɜːrstli/",
    type: "adv.",
    eng: "firstly",
  },
  {
    vn: "việc câu cá",
    pronounce: "/ˈfɪʃɪŋ/",
    type: "n.",
    eng: "fishing",
  },
  {
    vn: "vừa vặn; thích hợp",
    pronounce: "/fɪt/",
    type: "v., adj.",
    eng: "fit",
  },
  {
    vn: "sửa chữa, vá",
    pronounce: "/fɪks/",
    type: "v.",
    eng: "fix",
  },
  {
    vn: "phẳng, bằng phẳng",
    pronounce: "/flæt/",
    type: "adj.",
    eng: "flat",
  },
  {
    vn: "cúm",
    pronounce: "/fluː/",
    type: "n.",
    eng: "flu",
  },
  {
    vn: "con ruồi",
    pronounce: "/flaɪ/",
    type: "n.",
    eng: "fly",
  },
  {
    vn: "sự bay; đang bay",
    pronounce: "/ˈflaɪɪŋ/",
    type: "n., adj.",
    eng: "flying",
  },
  {
    vn: "tập trung; trung tâm",
    pronounce: "/ˈfoʊkəs/",
    type: "v., n.",
    eng: "focus",
  },
  {
    vn: "tiếp theo, sau đó",
    pronounce: "/ˈfɒloʊɪŋ/",
    type: "adj.",
    eng: "following",
  },
  {
    vn: "nước ngoài",
    pronounce: "/ˈfɔːrɪn/",
    type: "adj.",
    eng: "foreign",
  },
  {
    vn: "rừng",
    pronounce: "/ˈfɔːrɪst/",
    type: "n.",
    eng: "forest",
  },
  {
    vn: "tổng quát, chung",
    pronounce: "/ˈdʒɛnərəl/",
    type: "adj.",
    eng: "general",
  },
  {
    vn: "món quà",
    pronounce: "/ɡɪft/",
    type: "n.",
    eng: "gift",
  },
  {
    vn: "mục tiêu",
    pronounce: "/ɡoʊl/",
    type: "n.",
    eng: "goal",
  },
  {
    vn: "thần, Chúa",
    pronounce: "/ɡɒd/",
    type: "n.",
    eng: "god",
  },
  {
    vn: "cái nĩa",
    pronounce: "/fɔːrk/",
    type: "n.",
    eng: "fork",
  },
  {
    vn: "trang trọng, chính thức",
    pronounce: "/ˈfɔːrməl/",
    type: "adj.",
    eng: "formal",
  },
  {
    vn: "may mắn",
    pronounce: "/ˈfɔːrtʃənətli/",
    type: "adv.",
    eng: "fortunately",
  },
  {
    vn: "về phía trước",
    pronounce: "/ˈfɔːrwərd/",
    type: "adv.",
    eng: "forward",
  },
  {
    vn: "tươi mới",
    pronounce: "/frɛʃ/",
    type: "adj.",
    eng: "fresh",
  },
  {
    vn: "tủ lạnh",
    pronounce: "/frɪdʒ/",
    type: "n.",
    eng: "fridge",
  },
  {
    vn: "con ếch",
    pronounce: "/frɒɡ/",
    type: "n.",
    eng: "frog",
  },
  {
    vn: "đồ đạc, nội thất",
    pronounce: "/ˈfɜːrnɪtʃər/",
    type: "n.",
    eng: "furniture",
  },
  {
    vn: "xa hơn",
    pronounce: "/ˈfɜːrðər/",
    type: "adj.",
    eng: "further",
  },
  {
    vn: "phòng trưng bày, triển lãm",
    pronounce: "/ˈɡæləri/",
    type: "n.",
    eng: "gallery",
  },

  {
    vn: "hàng ngày",
    pronounce: "/ˈdeɪli/",
    type: "adj.",
    eng: "daily",
  },
  {
    vn: "nguy hiểm",
    pronounce: "/ˈdeɪndʒər/",
    type: "n.",
    eng: "danger",
  },
  {
    vn: "bóng tối",
    pronounce: "/dɑːrk/",
    type: "adj.",
    eng: "dark",
  },
  {
    vn: "chết",
    pronounce: "/dɛd/",
    type: "adj.",
    eng: "dead",
  },
  {
    vn: "giao dịch",
    pronounce: "/diːl/",
    type: "v.",
    eng: "deal",
  },
  {
    vn: "cái chết",
    pronounce: "/dɛθ/",
    type: "n.",
    eng: "death",
  },
  {
    vn: "quyết định",
    pronounce: "/dɪˈsɪʒən/",
    type: "n.",
    eng: "decision",
  },
  {
    vn: "sâu",
    pronounce: "/diːp/",
    type: "adj.",
    eng: "deep",
  },
  {
    vn: "chắc chắn",
    pronounce: "/ˈdɛfɪnɪtli/",
    type: "adv.",
    eng: "definitely",
  },
  {
    vn: "bằng cấp",
    pronounce: "/dɪˈɡriː/",
    type: "n.",
    eng: "degree",
  },
  {
    vn: "nha sĩ",
    pronounce: "/ˈdɛntɪst/",
    type: "n.",
    eng: "dentist",
  },
  {
    vn: "bộ phận",
    pronounce: "/dɪˈpɑːrtmənt/",
    type: "n.",
    eng: "department",
  },
  {
    vn: "phụ thuộc",
    pronounce: "/dɪˈpɛnd/",
    type: "v.",
    eng: "depend",
  },
  {
    vn: "sa mạc",
    pronounce: "/ˈdɛzərt/",
    type: "n.",
    eng: "desert",
  },
  {
    vn: "nhà thiết kế",
    pronounce: "/dɪˈzaɪnər/",
    type: "n.",
    eng: "designer",
  },
  {
    vn: "phá hủy",
    pronounce: "/dɪˈstrɔɪ/",
    type: "v.",
    eng: "destroy",
  },
  {
    vn: "thám tử",
    pronounce: "/dɪˈtɛktɪv/",
    type: "n.",
    eng: "detective",
  },
  {
    vn: "phát triển",
    pronounce: "/dɪˈvɛləp/",
    type: "v.",
    eng: "develop",
  },
  {
    vn: "thiết bị",
    pronounce: "/dɪˈvaɪs/",
    type: "n.",
    eng: "device",
  },
  {
    vn: "nhật ký",
    pronounce: "/ˈdaɪəri/",
    type: "n.",
    eng: "diary",
  },
  {
    vn: "một cách khác biệt",
    pronounce: "/ˈdɪfərəntli/",
    type: "adv.",
    eng: "differently",
  },
  {
    vn: "kỹ thuật số",
    pronounce: "/ˈdɪdʒɪtl̩/",
    type: "adj.",
    eng: "digital",
  },
  {
    vn: "trực tiếp",
    pronounce: "/dɪˈrɛkt/",
    type: "adj.",
    eng: "direct",
  },
  {
    vn: "hướng, phương hướng",
    pronounce: "/dɪˈrɛkʃən/",
    type: "n.",
    eng: "direction",
  },
  {
    vn: "giám đốc",
    pronounce: "/dɪˈrɛktər/",
    type: "n.",
    eng: "director",
  },
  {
    vn: "không đồng ý",
    pronounce: "/ˌdɪsəˈɡriː/",
    type: "v.",
    eng: "disagree",
  },
  {
    vn: "biến mất",
    pronounce: "/ˌdɪsəˈpɪr/",
    type: "v.",
    eng: "disappear",
  },
  {
    vn: "thảm họa",
    pronounce: "/dɪˈzæstər/",
    type: "n.",
    eng: "disaster",
  },
];
