var vocabulary1 = [
  { vn: "một", pronounce: "/ə/", type: "indefinite article", eng: "a" },
  { vn: "về", pronounce: "/əˈbaʊt/", type: "preposition", eng: "about" },
  { vn: "một", pronounce: "/ən/", type: "indefinite article", eng: "an" },
  { vn: "trên", pronounce: "/əˈbʌv/", type: "prep., adv.", eng: "above" },
  {
    vn: "qua, ngang qua",
    pronounce: "/əˈkrɔs/",
    type: "prep., adv.",
    eng: "across",
  },
  { vn: "hành động", pronounce: "/ˈækʃən/", type: "n.", eng: "action" },
  {
    vn: "hoạt động",
    pronounce: "/ækˈtɪvɪti/",
    type: "n.",
    eng: "activity",
  },
  {
    vn: "diễn viên nam",
    pronounce: "/ˈæktər/",
    type: "n.",
    eng: "actor",
  },
  {
    vn: "diễn viên nữ",
    pronounce: "/ˈæktrɪs/",
    type: "n.",
    eng: "actress",
  },
  { vn: "thêm vào", pronounce: "/æd/", type: "v.", eng: "add" },
  { vn: "địa chỉ", pronounce: "/ˈæˌdrɛs/", type: "n.", eng: "address" },
  { vn: "người lớn", pronounce: "/əˈdʌlt/", type: "n.", eng: "adult" },
  { vn: "lời khuyên", pronounce: "/ædˈvaɪs/", type: "n.", eng: "advice" },
  { vn: "sợ hãi", pronounce: "/əˈfreɪd/", type: "adj.", eng: "afraid" },
  { vn: "sau", pronounce: "/ˈæftər/", type: "prep.", eng: "after" },
  {
    vn: "buổi chiều",
    pronounce: "/ˌæftərˈnun/",
    type: "n.",
    eng: "afternoon",
  },
  { vn: "lại", pronounce: "/əˈgɛn/", type: "adv.", eng: "again" },
  { vn: "tuổi", pronounce: "/eɪʤ/", type: "n.", eng: "age" },
  { vn: "trước đây", pronounce: "/əˈgoʊ/", type: "adv.", eng: "ago" },
  { vn: "đồng ý", pronounce: "/əˈgri/", type: "v.", eng: "agree" },
  { vn: "không khí", pronounce: "/ɛr/", type: "n.", eng: "air" },
  { vn: "sân bay", pronounce: "/ˈɛrˌpɔrt/", type: "n.", eng: "airport" },
  { vn: "tất cả", pronounce: "/ɔl/", type: "det., pron.", eng: "all" },
  { vn: "cũng", pronounce: "/ˈɔlˌsoʊ/", type: "adv.", eng: "also" },
  {
    vn: "luôn luôn",
    pronounce: "/ˈɔlˌweɪz/",
    type: "adv.",
    eng: "always",
  },
  {
    vn: "tuyệt vời",
    pronounce: "/əˈmeɪzɪŋ/",
    type: "adj.",
    eng: "amazing",
  },
  { vn: "và", pronounce: "/ænd/", type: "conj.", eng: "and" },
  { vn: "tức giận", pronounce: "/ˈæŋgri/", type: "adj.", eng: "angry" },
  { vn: "động vật", pronounce: "/ˈænəməl/", type: "n.", eng: "animal" },
  {
    vn: "khác",
    pronounce: "/əˈnʌðər/",
    type: "det./pron.",
    eng: "another",
  },
  {
    vn: "câu trả lời, trả lời",
    pronounce: "/ˈænsər/",
    type: "n., v.",
    eng: "answer",
  },
  { vn: "bất kỳ", pronounce: "/ˈɛni/", type: "det., pron.", eng: "any" },
  {
    vn: "bất kỳ ai",
    pronounce: "/ˈɛniˌwʌn/",
    type: "pron.",
    eng: "anyone",
  },
  {
    vn: "bất cứ điều gì",
    pronounce: "/ˈɛniˌθɪŋ/",
    type: "pron.",
    eng: "anything",
  },
  {
    vn: "căn hộ",
    pronounce: "/əˈpɑrtmənt/",
    type: "n.",
    eng: "apartment",
  },
  { vn: "quả táo", pronounce: "/ˈæpəl/", type: "n.", eng: "apple" },
  { vn: "tháng Tư", pronounce: "/ˈeɪprəl/", type: "n.", eng: "April" },
  { vn: "khu vực", pronounce: "/ˈɛriə/", type: "n.", eng: "area" },
  { vn: "cánh tay", pronounce: "/ɑrm/", type: "n.", eng: "arm" },
  {
    vn: "xung quanh",
    pronounce: "/əˈraʊnd/",
    type: "prep., adv.",
    eng: "around",
  },
  { vn: "đến", pronounce: "/əˈraɪv/", type: "v.", eng: "arrive" },
  { vn: "nghệ thuật", pronounce: "/ɑrt/", type: "n.", eng: "art" },
  { vn: "bài báo", pronounce: "/ˈɑrtɪkəl/", type: "n.", eng: "article" },
  { vn: "nghệ sĩ", pronounce: "/ˈɑrtɪst/", type: "n.", eng: "artist" },
  { vn: "như", pronounce: "/æz/", type: "prep.", eng: "as" },
  { vn: "hỏi", pronounce: "/æsk/", type: "v.", eng: "ask" },
  { vn: "tại", pronounce: "/æt/", type: "prep.", eng: "at" },
  { vn: "tháng Tám", pronounce: "/ˈɔgəst/", type: "n.", eng: "August" },
  { vn: "cô, dì", pronounce: "/ænt/", type: "n.", eng: "aunt" },
  { vn: "mùa thu", pronounce: "/ˈɔtəm/", type: "n.", eng: "autumn" },
  { vn: "xa", pronounce: "/əˈweɪ/", type: "adv.", eng: "away" },
];

var vocabulary2 = [
  {
    vn: "lưng, mặt sau",
    pronounce: "/bæk/",
    type: "n., adv.",
    eng: "back",
  },
  { vn: "xấu", pronounce: "/bæd/", type: "adj.", eng: "bad, worse, worst" },
  { vn: "túi", pronounce: "/bæg/", type: "n.", eng: "bag" },
  { vn: "quả bóng", pronounce: "/bɔl/", type: "n.", eng: "ball" },
  { vn: "ban nhạc", pronounce: "/bænd/", type: "n.", eng: "band" },
  {
    vn: "ngân hàng",
    pronounce: "/bæŋk/",
    type: "n.",
    eng: "bank (money)",
  },
  { vn: "bồn tắm", pronounce: "/bæθ/", type: "n.", eng: "bath" },
  {
    vn: "phòng tắm",
    pronounce: "/ˈbæθˌrum/",
    type: "n.",
    eng: "bathroom",
  },
  {
    vn: "là, thì, ở",
    pronounce: "/bi/",
    type: "v., auxiliary v.",
    eng: "be",
  },
  { vn: "bãi biển", pronounce: "/biʧ/", type: "n.", eng: "beach" },
  { vn: "đẹp", pronounce: "/ˈbjutəfəl/", type: "adj.", eng: "beautiful" },
  { vn: "bởi vì", pronounce: "/bɪˈkɔz/", type: "conj.", eng: "because" },
  { vn: "trở thành", pronounce: "/bɪˈkʌm/", type: "v.", eng: "become" },
  { vn: "giường", pronounce: "/bɛd/", type: "n.", eng: "bed" },
  {
    vn: "phòng ngủ",
    pronounce: "/ˈbɛdˌrum/",
    type: "n.",
    eng: "bedroom",
  },
  { vn: "bia", pronounce: "/bɪr/", type: "n.", eng: "beer" },
  { vn: "trước", pronounce: "/bɪˈfɔr/", type: "prep.", eng: "before" },
  { vn: "bắt đầu", pronounce: "/bɪˈgɪn/", type: "v.", eng: "begin" },
  {
    vn: "sự bắt đầu",
    pronounce: "/bɪˈgɪnɪŋ/",
    type: "n.",
    eng: "beginning",
  },
  {
    vn: "phía sau",
    pronounce: "/bɪˈhaɪnd/",
    type: "prep., adv.",
    eng: "behind",
  },
  { vn: "tin tưởng", pronounce: "/bɪˈliv/", type: "v.", eng: "believe" },
  {
    vn: "dưới",
    pronounce: "/bɪˈloʊ/",
    type: "adv., prep.",
    eng: "below",
  },
  { vn: "tốt nhất", pronounce: "/bɛst/", type: "adj.", eng: "best" },
  { vn: "tốt hơn", pronounce: "/ˈbɛtər/", type: "adj.", eng: "better" },
  { vn: "giữa", pronounce: "/bɪˈtwin/", type: "prep.", eng: "between" },
  { vn: "lớn", pronounce: "/bɪg/", type: "adj.", eng: "big" },
  { vn: "hóa đơn", pronounce: "/bɪl/", type: "n.", eng: "bill" },
  { vn: "chim", pronounce: "/bɜrd/", type: "n.", eng: "bird" },
  { vn: "blog", pronounce: "/blɔg/", type: "n.", eng: "blog" },
  { vn: "vàng (tóc)", pronounce: "/blɑnd/", type: "adj.", eng: "blonde" },
  { vn: "thuyền", pronounce: "/boʊt/", type: "n.", eng: "boat" },
  { vn: "sách", pronounce: "/bʊk/", type: "n.", eng: "book" },
  { vn: "ủng", pronounce: "/but/", type: "n.", eng: "boot" },
  { vn: "chán", pronounce: "/bɔrd/", type: "adj.", eng: "bored" },
  { vn: "nhàm chán", pronounce: "/ˈbɔrɪŋ/", type: "adj.", eng: "boring" },
  { vn: "sinh ra", pronounce: "/bɔrn/", type: "v.", eng: "born" },
  { vn: "cả hai", pronounce: "/boʊθ/", type: "det./pron.", eng: "both" },
  { vn: "chai", pronounce: "/ˈbɑtəl/", type: "n.", eng: "bottle" },
  { vn: "hộp", pronounce: "/bɑks/", type: "n.", eng: "box" },
  { vn: "bánh mì", pronounce: "/brɛd/", type: "n.", eng: "bread" },
  {
    vn: "sự giả lao, nghỉ giải lao",
    pronounce: "/breɪk/",
    type: "v., n.",
    eng: "break",
  },
  {
    vn: "chia tay",
    pronounce: "/breɪk/",
    type: "v., n.",
    eng: "break up",
  },
  {
    vn: "bữa sáng",
    pronounce: "/ˈbrɛkfəst/",
    type: "n.",
    eng: "breakfast",
  },
  { vn: "mang đến", pronounce: "/brɪŋ/", type: "v.", eng: "bring" },
  {
    vn: "nâu, màu nâu",
    pronounce: "/braʊn/",
    type: "adj., n.",
    eng: "brown",
  },
  { vn: "xây dựng", pronounce: "/bɪld/", type: "v.", eng: "build" },
  { vn: "tòa nhà", pronounce: "/ˈbɪldɪŋ/", type: "n.", eng: "building" },
  {
    vn: "kinh doanh",
    pronounce: "/ˈbɪznɪs/",
    type: "n.",
    eng: "business",
  },
  { vn: "bận rộn", pronounce: "/ˈbɪzi/", type: "adj.", eng: "busy" },
  { vn: "nhưng", pronounce: "/bʌt/", type: "conj.", eng: "but" },
  { vn: "bơ", pronounce: "/ˈbʌtər/", type: "n.", eng: "butter" },
  { vn: "mua", pronounce: "/baɪ/", type: "v.", eng: "buy" },
  { vn: "bởi, gần", pronounce: "/baɪ/", type: "prep.", eng: "by" },
];

const vocabulary3 = [
  { vn: "quán cà phê", pronounce: "/kæˈfeɪ/", type: "n.", eng: "cafe" },
  { vn: "bánh ngọt", pronounce: "/keɪk/", type: "n.", eng: "cake" },
  {
    vn: "gọi, cuộc gọi",
    pronounce: "/kɔl/",
    type: "v., n.",
    eng: "call",
  },
  { vn: "máy ảnh", pronounce: "/ˈkæmərə/", type: "n.", eng: "camera" },
  { vn: "có thể", pronounce: "/kæn/", type: "modal v.", eng: "can" },
  {
    vn: "không thể",
    pronounce: "/ˈkænˌnɒt/",
    type: "modal v.",
    eng: "cannot",
  },
  {
    vn: "thủ đô, viết hoa",
    pronounce: "/ˈkæpɪtəl/",
    type: "n., adj.",
    eng: "capital",
  },
  { vn: "xe hơi", pronounce: "/kɑr/", type: "n.", eng: "car" },
  { vn: "thẻ, thiệp", pronounce: "/kɑrd/", type: "n.", eng: "card" },
  { vn: "sự nghiệp", pronounce: "/kəˈrɪr/", type: "n.", eng: "career" },
  { vn: "cà rốt", pronounce: "/ˈkærət/", type: "n.", eng: "carrot" },
  { vn: "mang", pronounce: "/ˈkæri/", type: "v.", eng: "carry" },
  { vn: "con mèo", pronounce: "/kæt/", type: "n.", eng: "cat" },
  { vn: "đĩa CD", pronounce: "/ˌsiːˈdiː/", type: "n.", eng: "CD" },
  {
    vn: "xu (đơn vị tiền tệ)",
    pronounce: "/sɛnt/",
    type: "n.",
    eng: "cent",
  },
  { vn: "trung tâm", pronounce: "/ˈsɛntər/", type: "n.", eng: "centre" },
  { vn: "thế kỷ", pronounce: "/ˈsɛnʧəri/", type: "n.", eng: "century" },
  { vn: "ghế", pronounce: "/ʧɛr/", type: "n.", eng: "chair" },
  {
    vn: "thay đổi, sự thay đổi",
    pronounce: "/ʧeɪnʤ/",
    type: "v., n.",
    eng: "change",
  },
  { vn: "biểu đồ", pronounce: "/ʧɑrt/", type: "n.", eng: "chart" },
  { vn: "rẻ", pronounce: "/ʧip/", type: "adj.", eng: "cheap" },
  { vn: "kiểm tra", pronounce: "/ʧɛk/", type: "v.", eng: "check" },
  { vn: "phô mai", pronounce: "/ʧiz/", type: "n.", eng: "cheese" },
  { vn: "gà", pronounce: "/ˈʧɪkɪn/", type: "n.", eng: "chicken" },
  { vn: "trẻ em", pronounce: "/ʧaɪld/", type: "n.", eng: "child" },
  {
    vn: "sô cô la",
    pronounce: "/ˈʧɔklət/",
    type: "n.",
    eng: "chocolate",
  },
  { vn: "chọn", pronounce: "/ʧuz/", type: "v.", eng: "choose" },
  {
    vn: "rạp chiếu phim",
    pronounce: "/ˈsɪnəmə/",
    type: "n.",
    eng: "cinema",
  },
  { vn: "thành phố", pronounce: "/ˈsɪti/", type: "n.", eng: "city" },
  { vn: "lớp học", pronounce: "/klæs/", type: "n.", eng: "class" },
  {
    vn: "phòng học",
    pronounce: "/ˈklæsˌrum/",
    type: "n.",
    eng: "classroom",
  },
  {
    vn: "sạch sẽ, làm sạch",
    pronounce: "/klin/",
    type: "adj., v.",
    eng: "clean",
  },
  { vn: "leo", pronounce: "/klaɪm/", type: "v.", eng: "climb" },
  { vn: "đồng hồ", pronounce: "/klɑk/", type: "n.", eng: "clock" },
  { vn: "đóng", pronounce: "/kloʊs/", type: "v.", eng: "close" },
  { vn: "quần áo", pronounce: "/kloʊðz/", type: "n.", eng: "clothes" },
  { vn: "câu lạc bộ", pronounce: "/klʌb/", type: "n.", eng: "club" },
  { vn: "áo khoác", pronounce: "/koʊt/", type: "n.", eng: "coat" },
  { vn: "cà phê", pronounce: "/ˈkɔfi/", type: "n.", eng: "coffee" },
  {
    vn: "lạnh, cảm lạnh",
    pronounce: "/koʊld/",
    type: "adj., n.",
    eng: "cold",
  },
  {
    vn: "trường cao đẳng, đại học",
    pronounce: "/ˈkɑlɪʤ/",
    type: "n.",
    eng: "college",
  },
  { vn: "màu sắc", pronounce: "/ˈkʌlər/", type: "n.", eng: "colour" },
  { vn: "đến", pronounce: "/kʌm/", type: "v.", eng: "come" },
  {
    vn: "phổ biến, thông thường",
    pronounce: "/ˈkɑmən/",
    type: "adj.",
    eng: "common",
  },
  { vn: "công ty", pronounce: "/ˈkʌmpəni/", type: "n.", eng: "company" },
  { vn: "so sánh", pronounce: "/kəmˈpɛr/", type: "v.", eng: "compare" },
  {
    vn: "hoàn thành, hoàn chỉnh",
    pronounce: "/kəmˈplit/",
    type: "adj., v.",
    eng: "complete",
  },
  {
    vn: "máy tính",
    pronounce: "/kəmˈpjutər/",
    type: "n.",
    eng: "computer",
  },
  {
    vn: "buổi hòa nhạc",
    pronounce: "/ˈkɑnsərt/",
    type: "n.",
    eng: "concert",
  },
  {
    vn: "cuộc trò chuyện",
    pronounce: "/ˌkɑnvərˈseɪʃən/",
    type: "n.",
    eng: "conversation",
  },
  { vn: "nấu ăn", pronounce: "/kʊk/", type: "v.", eng: "cook" },
  {
    vn: "việc nấu ăn",
    pronounce: "/ˈkʊkɪŋ/",
    type: "n.",
    eng: "cooking",
  },
  { vn: "mát mẻ", pronounce: "/kul/", type: "adj.", eng: "cool" },
  {
    vn: "đúng, sửa",
    pronounce: "/kəˈrɛkt/",
    type: "adj., v.",
    eng: "correct",
  },
  {
    vn: "giá cả, tốn kém",
    pronounce: "/kɔst/",
    type: "n., v.",
    eng: "cost",
  },
  {
    vn: "có thể (quá khứ của can)",
    pronounce: "/kʊd/",
    type: "modal v.",
    eng: "could",
  },
  { vn: "đất nước", pronounce: "/ˈkʌntri/", type: "n.", eng: "country" },
  { vn: "khóa học", pronounce: "/kɔrs/", type: "n.", eng: "course" },
  {
    vn: "anh chị em họ",
    pronounce: "/ˈkʌzən/",
    type: "n.",
    eng: "cousin",
  },
  { vn: "con bò", pronounce: "/kaʊ/", type: "n.", eng: "cow" },
  { vn: "kem", pronounce: "/krim/", type: "n.", eng: "cream" },
  { vn: "tạo ra", pronounce: "/kriˈeɪt/", type: "v.", eng: "create" },
  { vn: "văn hóa", pronounce: "/ˈkʌlʧər/", type: "n.", eng: "culture" },
  { vn: "tách, cốc", pronounce: "/kʌp/", type: "n.", eng: "cup" },
  {
    vn: "khách hàng",
    pronounce: "/ˈkʌstəmər/",
    type: "n.",
    eng: "customer",
  },
  { vn: "cắt", pronounce: "/kʌt/", type: "v.", eng: "cut" },
];

var vocabulary4 = [
  {
    vn: "nhảy múa, điệu nhảy",
    pronounce: "/dæns/",
    type: "n., v.",
    eng: "dance",
  },
  {
    vn: "vũ công",
    pronounce: "/ˈdænsər/",
    type: "n.",
    eng: "dancer",
  },
  {
    vn: "việc nhảy múa",
    pronounce: "/ˈdænsɪŋ/",
    type: "n.",
    eng: "dancing",
  },
  {
    vn: "nguy hiểm",
    pronounce: "/ˈdeɪnʤərəs/",
    type: "adj.",
    eng: "dangerous",
  },
  {
    vn: "tối",
    pronounce: "/dɑrk/",
    type: "adj.",
    eng: "dark",
  },
  {
    vn: "ngày, cuộc hẹn",
    pronounce: "/deɪt/",
    type: "n.",
    eng: "date",
  },
  {
    vn: "con gái",
    pronounce: "/ˈdɔtər/",
    type: "n.",
    eng: "daughter",
  },
  {
    vn: "ngày",
    pronounce: "/deɪ/",
    type: "n.",
    eng: "day",
  },
  {
    vn: "thân yêu, quý mến",
    pronounce: "/dɪr/",
    type: "adj.",
    eng: "dear",
  },
  {
    vn: "tháng mười hai",
    pronounce: "/dɪˈsɛmbər/",
    type: "n.",
    eng: "December",
  },
  {
    vn: "quyết định",
    pronounce: "/dɪˈsaɪd/",
    type: "v.",
    eng: "decide",
  },
  {
    vn: "ngon",
    pronounce: "/dɪˈlɪʃəs/",
    type: "adj.",
    eng: "delicious",
  },
  {
    vn: "mô tả",
    pronounce: "/dɪˈskraɪb/",
    type: "v.",
    eng: "describe",
  },
  {
    vn: "sự mô tả",
    pronounce: "/dɪˈskrɪpʃən/",
    type: "n.",
    eng: "description",
  },
  {
    vn: "thiết kế",
    pronounce: "/dɪˈzaɪn/",
    type: "n., v.",
    eng: "design",
  },
  {
    vn: "bàn làm việc",
    pronounce: "/dɛsk/",
    type: "n.",
    eng: "desk",
  },
  {
    vn: "chi tiết",
    pronounce: "/ˈdiˌteɪl/",
    type: "n.",
    eng: "detail",
  },
  {
    vn: "cuộc đối thoại",
    pronounce: "/ˈdaɪəˌlɔg/",
    type: "n.",
    eng: "dialogue",
  },
  {
    vn: "từ điển",
    pronounce: "/ˈdɪkʃəˌnɛri/",
    type: "n.",
    eng: "dictionary",
  },
  {
    vn: "chế độ ăn kiêng",
    pronounce: "/ˈdaɪət/",
    type: "n.",
    eng: "diet",
  },
  {
    vn: "sự khác biệt",
    pronounce: "/ˈdɪfərəns/",
    type: "n.",
    eng: "difference",
  },
  {
    vn: "khác",
    pronounce: "/ˈdɪfərənt/",
    type: "adj.",
    eng: "different",
  },
  {
    vn: "khó khăn",
    pronounce: "/ˈdɪfəkəlt/",
    type: "adj.",
    eng: "difficult",
  },
  {
    vn: "bữa tối",
    pronounce: "/ˈdɪnər/",
    type: "n.",
    eng: "dinner",
  },
  {
    vn: "bẩn",
    pronounce: "/ˈdɜrti/",
    type: "adj.",
    eng: "dirty",
  },
  {
    vn: "thảo luận",
    pronounce: "/dɪˈskʌs/",
    type: "v.",
    eng: "discuss",
  },
  {
    vn: "món ăn, đĩa",
    pronounce: "/dɪʃ/",
    type: "n.",
    eng: "dish",
  },
  {
    vn: "làm",
    pronounce: "/du/",
    type: "v., auxiliary v.",
    eng: "do",
  },
  {
    vn: "cửa",
    pronounce: "/dɔr/",
    type: "n.",
    eng: "door",
  },
  {
    vn: "xuống",
    pronounce: "/daʊn/",
    type: "adv., prep.",
    eng: "down",
  },
  {
    vn: "tầng dưới",
    pronounce: "/ˈdaʊnˌstɛrz/",
    type: "adv.",
    eng: "downstairs",
  },
  {
    vn: "vẽ",
    pronounce: "/drɔ/",
    type: "v.",
    eng: "draw",
  },
  {
    vn: "váy, mặc",
    pronounce: "/drɛs/",
    type: "n., v.",
    eng: "dress",
  },
  {
    vn: "đồ uống, uống",
    pronounce: "/drɪŋk/",
    type: "n., v.",
    eng: "drink",
  },
  {
    vn: "lái xe",
    pronounce: "/draɪv/",
    type: "v.",
    eng: "drive",
  },
  {
    vn: "tài xế",
    pronounce: "/ˈdraɪvər/",
    type: "n.",
    eng: "driver",
  },
  {
    vn: "trong suốt, trong lúc, trong khoảng",
    pronounce: "/ˈdʊrɪŋ/",
    type: "prep.",
    eng: "during",
  },
  {
    vn: "mỗi",
    pronounce: "/iʧ/",
    type: "det./pron./adv.",
    eng: "each",
  },
  {
    vn: "tai",
    pronounce: "/ɪr/",
    type: "n.",
    eng: "ear",
  },
  {
    vn: "sớm",
    pronounce: "/ˈɜrli/",
    type: "adj., adv.",
    eng: "early",
  },
  {
    vn: "phía đông",
    pronounce: "/ist/",
    type: "n., adj., adv.",
    eng: "east",
  },
  {
    vn: "dễ dàng",
    pronounce: "/ˈizi/",
    type: "adj.",
    eng: "easy",
  },
  {
    vn: "ăn",
    pronounce: "/it/",
    type: "v.",
    eng: "eat",
  },
  {
    vn: "trứng",
    pronounce: "/ɛg/",
    type: "n.",
    eng: "egg",
  },
  {
    vn: "số tám",
    pronounce: "/eɪt/",
    type: "number.",
    eng: "eight",
  },
  {
    vn: "số mười tám",
    pronounce: "/ˈeɪˈtin/",
    type: "number.",
    eng: "eighteen",
  },
  {
    vn: "số tám mươi",
    pronounce: "/ˈeɪti/",
    type: "number.",
    eng: "eighty",
  },
  {
    vn: "con voi",
    pronounce: "/ˈɛləfənt/",
    type: "n.",
    eng: "elephant",
  },
  {
    vn: "số mười một",
    pronounce: "/ɪˈlɛvən/",
    type: "number.",
    eng: "eleven",
  },
  {
    vn: "khác",
    pronounce: "/ɛls/",
    type: "adv.",
    eng: "else",
  },
  {
    vn: "kết thúc",
    pronounce: "/ɛnd/",
    type: "n., v.",
    eng: "end",
  },
  {
    vn: "thích thú, thưởng thức",
    pronounce: "/ɛnˈʤɔɪ/",
    type: "v.",
    eng: "enjoy",
  },
  {
    vn: "đủ",
    pronounce: "/ɪˈnʌf/",
    type: "det., pron., adv.",
    eng: "enough",
  },
  {
    vn: "đồng euro",
    pronounce: "/ˈjʊroʊ/",
    type: "n.",
    eng: "euro",
  },
  {
    vn: "thậm chí, ngay cả",
    pronounce: "/ˈiːvən/",
    type: "adv.",
    eng: "even",
  },
  {
    vn: "buổi tối",
    pronounce: "/ˈiːvnɪŋ/",
    type: "n.",
    eng: "evening",
  },
  {
    vn: "sự kiện",
    pronounce: "/ɪˈvɛnt/",
    type: "n.",
    eng: "event",
  },
  {
    vn: "từng",
    pronounce: "/ˈɛvər/",
    type: "adv.",
    eng: "ever",
  },
  {
    vn: "mọi",
    pronounce: "/ˈɛvri/",
    type: "det.",
    eng: "every",
  },
  {
    vn: "mọi người",
    pronounce: "/ˈɛvriˌbɑdi/",
    type: "pron.",
    eng: "everybody",
  },
  {
    vn: "mọi người",
    pronounce: "/ˈɛvriˌwʌn/",
    type: "pron.",
    eng: "everyone",
  },
  {
    vn: "mọi thứ",
    pronounce: "/ˈɛvriˌθɪŋ/",
    type: "pron.",
    eng: "everything",
  },
  {
    vn: "kỳ thi",
    pronounce: "/ɪɡˈzæm/",
    type: "n.",
    eng: "exam",
  },
  {
    vn: "ví dụ",
    pronounce: "/ɪɡˈzæmpəl/",
    type: "n.",
    eng: "example",
  },
  {
    vn: "hào hứng",
    pronounce: "/ɪkˈsaɪtɪd/",
    type: "adj.",
    eng: "excited",
  },
  {
    vn: "thú vị",
    pronounce: "/ɪkˈsaɪtɪŋ/",
    type: "adj.",
    eng: "exciting",
  },
  {
    vn: "tập thể dục, bài tập",
    pronounce: "/ˈɛksərˌsaɪz/",
    type: "n., v.",
    eng: "exercise",
  },
  {
    vn: "đắt đỏ",
    pronounce: "/ɪkˈspɛnsɪv/",
    type: "adj.",
    eng: "expensive",
  },
  {
    vn: "giải thích",
    pronounce: "/ɪkˈspleɪn/",
    type: "v.",
    eng: "explain",
  },
  {
    vn: "thêm",
    pronounce: "/ˈɛkstrə/",
    type: "adj.",
    eng: "extra",
  },
  {
    vn: "mắt",
    pronounce: "/aɪ/",
    type: "n.",
    eng: "eye",
  },
  {
    vn: "khuôn mặt",
    pronounce: "/feɪs/",
    type: "n.",
    eng: "face",
  },
  {
    vn: "sự thật",
    pronounce: "/fækt/",
    type: "n.",
    eng: "fact",
  },
  {
    vn: "ngã, rơi",
    pronounce: "/fɔl/",
    type: "v.",
    eng: "fall",
  },
  {
    vn: "gia đình",
    pronounce: "/ˈfæməli/",
    type: "n., adj.",
    eng: "family",
  },
  {
    vn: "nổi tiếng",
    pronounce: "/ˈfeɪməs/",
    type: "adj.",
    eng: "famous",
  },
  {
    vn: "tuyệt vời",
    pronounce: "/fænˈtæstɪk/",
    type: "adj.",
    eng: "fantastic",
  },
  {
    vn: "xa",
    pronounce: "/fɑr/",
    type: "adv.",
    eng: "far,further,farther",
  },
  {
    vn: "trang trại,nông nghiệp",
    pronounce: "/fɑrm/",
    type: "n.",
    eng: "farm",
  },
  {
    vn: "nông dân",
    pronounce: "/ˈfɑrmər/",
    type: "n.",
    eng: "farmer",
  },
  {
    vn: "nhanh",
    pronounce: "/fæst/",
    type: "adj., adv.",
    eng: "fast",
  },
  {
    vn: "béo",
    pronounce: "/fæt/",
    type: "adj.",
    eng: "fat",
  },
  {
    vn: "bố",
    pronounce: "/ˈfɑðər/",
    type: "n.",
    eng: "father",
  },
  {
    vn: "yêu thích",
    pronounce: "/ˈfeɪvərɪt/",
    type: "adj., n.",
    eng: "favourite",
  },
  {
    vn: "tháng hai",
    pronounce: "/ˈfɛbjuˌɛri/",
    type: "n.",
    eng: "February",
  },
  {
    vn: "cảm thấy",
    pronounce: "/fil/",
    type: "v.",
    eng: "feel",
  },
  {
    vn: "cảm giác",
    pronounce: "/ˈfilɪŋ/",
    type: "n.",
    eng: "feeling",
  },
  {
    vn: "lễ hội",
    pronounce: "/ˈfɛstəvəl/",
    type: "n.",
    eng: "festival",
  },
  {
    vn: "một vài",
    pronounce: "/fju/",
    type: "det./adj., pron.",
    eng: "few",
  },
  {
    vn: "mười lăm",
    pronounce: "/ˈfɪfˌtin/",
    type: "number",
    eng: "fifteen",
  },
  { vn: "thứ năm", pronounce: "/fɪfθ/", type: "number", eng: "fifth" },
  { vn: "năm mươi", pronounce: "/ˈfɪfti/", type: "number", eng: "fifty" },
  { vn: "đổ đầy", pronounce: "/fɪl/", type: "verb", eng: "fill" },
  { vn: "phim", pronounce: "/fɪlm/", type: "noun", eng: "film" },
  {
    vn: "cuối cùng",
    pronounce: "/ˈfaɪnl/",
    type: "adjective",
    eng: "final",
  },
  { vn: "tìm thấy", pronounce: "/faɪnd/", type: "verb", eng: "find" },
  { vn: "tốt", pronounce: "/faɪn/", type: "adjective", eng: "fine" },
  { vn: "kết thúc", pronounce: "/ˈfɪnɪʃ/", type: "verb", eng: "finish" },
  { vn: "lửa", pronounce: "/faɪər/", type: "noun", eng: "fire" },
  {
    vn: "đầu tiên",
    pronounce: "/fɜːrst/",
    type: "determiner/number, adverb",
    eng: "first",
  },
  { vn: "cá", pronounce: "/fɪʃ/", type: "noun", eng: "fish" },
  { vn: "năm", pronounce: "/faɪv/", type: "number", eng: "five" },
  { vn: "căn hộ", pronounce: "/flæt/", type: "noun", eng: "flat" },
  { vn: "chuyến bay", pronounce: "/flaɪt/", type: "noun", eng: "flight" },
  { vn: "sàn nhà", pronounce: "/flɔːr/", type: "noun", eng: "floor" },
  { vn: "hoa", pronounce: "/ˈflaʊər/", type: "noun", eng: "flower" },
  { vn: "bay", pronounce: "/flaɪ/", type: "verb", eng: "fly" },
  { vn: "theo sau", pronounce: "/ˈfɑːloʊ/", type: "verb", eng: "follow" },
  { vn: "thức ăn", pronounce: "/fuːd/", type: "noun", eng: "food" },
  { vn: "bàn chân", pronounce: "/fʊt/", type: "noun", eng: "foot" },
  {
    vn: "bóng đá",
    pronounce: "/ˈfʊtˌbɔːl/",
    type: "noun",
    eng: "football",
  },
  { vn: "cho", pronounce: "/fɔːr/", type: "preposition", eng: "for" },
  { vn: "quên", pronounce: "/fərˈɡɛt/", type: "verb", eng: "forget" },
  {
    vn: "hình thức",
    pronounce: "/fɔːrm/",
    type: "noun, verb",
    eng: "form",
  },
  {
    vn: "bốn mươi",
    pronounce: "/ˈfɔːrti/",
    type: "number",
    eng: "forty",
  },
  { vn: "bốn", pronounce: "/fɔːr/", type: "number", eng: "four" },
  {
    vn: "mười bốn",
    pronounce: "/ˈfɔːrˌtin/",
    type: "number",
    eng: "fourteen",
  },
  { vn: "thứ tư", pronounce: "/fɔːrθ/", type: "number", eng: "fourth" },
  { vn: "miễn phí", pronounce: "/friː/", type: "adjective", eng: "free" },
  { vn: "thứ sáu", pronounce: "/ˈfraɪdeɪ/", type: "noun", eng: "Friday" },
  { vn: "bạn bè", pronounce: "/frɛnd/", type: "noun", eng: "friend" },
  {
    vn: "thân thiện",
    pronounce: "/ˈfrɛndli/",
    type: "adjective",
    eng: "friendly",
  },
  { vn: "từ", pronounce: "/frʌm/", type: "preposition", eng: "from" },
  {
    vn: "phía trước, mặt trước",
    pronounce: "/frʌnt/",
    type: "n., adj.",
    eng: "front",
  },
  {
    vn: "trái cây",
    pronounce: "/frut/",
    type: "n.",
    eng: "fruit",
  },
  {
    vn: "đầy",
    pronounce: "/fʊl/",
    type: "adj.",
    eng: "full",
  },
  {
    vn: "niềm vui",
    pronounce: "/fʌn/",
    type: "n.",
    eng: "fun",
  },
  {
    vn: "hài hước",
    pronounce: "/ˈfʌni/",
    type: "adj.",
    eng: "funny",
  },
  {
    vn: "tương lai",
    pronounce: "/ˈfjuʧər/",
    type: "n.",
    eng: "future",
  },
];

var vocabulary5 = [
  { vn: "trò chơi", pronounce: "/ɡeɪm/", type: "n.", eng: "game" },
  { vn: "khu vườn", pronounce: "/ˈɡɑrdn/", type: "n.", eng: "garden" },
  {
    vn: "địa lý",
    pronounce: "/ʤiˈɑɡrəfi/",
    type: "n.",
    eng: "geography",
  },
  { vn: "nhận, lấy", pronounce: "/ɡɛt/", type: "v.", eng: "get" },
  { vn: "cô gái", pronounce: "/ɡɜrl/", type: "n.", eng: "girl" },
  {
    vn: "bạn gái",
    pronounce: "/ˈɡɜrlˌfrɛnd/",
    type: "n.",
    eng: "girlfriend",
  },
  { vn: "đưa, tặng", pronounce: "/ɡɪv/", type: "v.", eng: "give" },
  { vn: "kính, ly", pronounce: "/ɡlæs/", type: "n.", eng: "glass" },
  { vn: "đi", pronounce: "/ɡoʊ/", type: "v.", eng: "go" },
  { vn: "tốt", pronounce: "/ɡʊd/", type: "adj.", eng: "good" },
  {
    vn: "tạm biệt",
    pronounce: "/ɡʊdˈbaɪ/",
    type: "exclam./n.",
    eng: "goodbye",
  },
  {
    vn: "ông",
    pronounce: "/ˈɡrændˌfɑðər/",
    type: "n.",
    eng: "grandfather",
  },
  {
    vn: "bà",
    pronounce: "/ˈɡrændˌmʌðər/",
    type: "n.",
    eng: "grandmother",
  },
  {
    vn: "ông bà",
    pronounce: "/ˈɡrændˌpɛrənt/",
    type: "n.",
    eng: "grandparent",
  },
  { vn: "tuyệt vời", pronounce: "/ɡreɪt/", type: "adj.", eng: "great" },
  {
    vn: "xanh lá cây",
    pronounce: "/ɡrin/",
    type: "adj., n.",
    eng: "green",
  },
  { vn: "xám", pronounce: "/ɡreɪ/", type: "adj., n.", eng: "grey" },
  { vn: "nhóm", pronounce: "/ɡrup/", type: "n.", eng: "group" },
  {
    vn: "phát triển, lớn lên",
    pronounce: "/ɡroʊ/",
    type: "v.",
    eng: "grow",
  },
  { vn: "đoán", pronounce: "/ɡɛs/", type: "v., n.", eng: "guess" },
  { vn: "đàn guitar", pronounce: "/ɡɪˈtɑr/", type: "n.", eng: "guitar" },
  { vn: "phòng tập thể dục", pronounce: "/ʤɪm/", type: "n.", eng: "gym" },
  { vn: "tóc", pronounce: "/hɛr/", type: "n.", eng: "hair" },
  {
    vn: "một nửa",
    pronounce: "/hæf/",
    type: "n., det./pron.",
    eng: "half",
  },
  { vn: "tay", pronounce: "/hænd/", type: "n.", eng: "hand" },
  { vn: "xảy ra", pronounce: "/ˈhæpən/", type: "v.", eng: "happen" },
  { vn: "hạnh phúc", pronounce: "/ˈhæpi/", type: "adj.", eng: "happy" },
  {
    vn: "khó khăn, chăm chỉ",
    pronounce: "/hɑrd/",
    type: "adj., adv.",
    eng: "hard",
  },
  { vn: "mũ", pronounce: "/hæt/", type: "n.", eng: "hat" },
  { vn: "ghét", pronounce: "/heɪt/", type: "v.", eng: "hate" },
  { vn: "có", pronounce: "/hæv/", type: "v.", eng: "have" },
  { vn: "phải", pronounce: "/hæv tu/", type: "modal v.", eng: "have to" },
  { vn: "anh ấy", pronounce: "/hi/", type: "pron.", eng: "he" },
  { vn: "đầu", pronounce: "/hɛd/", type: "n.", eng: "head" },
  { vn: "sức khỏe", pronounce: "/hɛlθ/", type: "n.", eng: "health" },
  {
    vn: "khỏe mạnh",
    pronounce: "/ˈhɛlθi/",
    type: "adj.",
    eng: "healthy",
  },
  { vn: "nghe", pronounce: "/hɪr/", type: "v.", eng: "hear" },
  {
    vn: "giúp đỡ, sự giúp đỡ",
    pronounce: "/hɛlp/",
    type: "v., n.",
    eng: "help",
  },
  {
    vn: "cô ấy, của cô ấy",
    pronounce: "/hər/",
    type: "pron., det.",
    eng: "her",
  },
  { vn: "ở đây", pronounce: "/hɪr/", type: "adv.", eng: "here" },
  { vn: "này", pronounce: "/heɪ/", type: "exclam.", eng: "hey" },
  { vn: "cao", pronounce: "/haɪ/", type: "adj.", eng: "high" },
  { vn: "anh ấy", pronounce: "/hɪm/", type: "pron.", eng: "him" },
  { vn: "của anh ấy", pronounce: "/hɪz/", type: "det.", eng: "his" },
  { vn: "lịch sử", pronounce: "/ˈhɪstəri/", type: "n.", eng: "history" },
  { vn: "sở thích", pronounce: "/ˈhɑbi/", type: "n.", eng: "hobby" },
  { vn: "kỳ nghỉ", pronounce: "/ˈhɑləˌdeɪ/", type: "n.", eng: "holiday" },
  { vn: "nhà", pronounce: "/hoʊm/", type: "n., adv.", eng: "home" },
  {
    vn: "bài tập về nhà",
    pronounce: "/ˈhoʊmˌwɜrk/",
    type: "n.",
    eng: "homework",
  },
  { vn: "hy vọng", pronounce: "/hoʊp/", type: "v.", eng: "hope" },
  { vn: "con ngựa", pronounce: "/hɔrs/", type: "n.", eng: "horse" },
  {
    vn: "bệnh viện",
    pronounce: "/ˈhɑˌspɪtl/",
    type: "n.",
    eng: "hospital",
  },
  { vn: "nóng", pronounce: "/hɑt/", type: "adj.", eng: "hot" },
  { vn: "khách sạn", pronounce: "/hoʊˈtɛl/", type: "n.", eng: "hotel" },
  { vn: "giờ", pronounce: "/ˈaʊər/", type: "n.", eng: "hour" },
  { vn: "nhà", pronounce: "/haʊs/", type: "n.", eng: "house" },
  { vn: "như thế nào", pronounce: "/haʊ/", type: "adv.", eng: "how" },
  {
    vn: "tuy nhiên",
    pronounce: "/haʊˈɛvər/",
    type: "adv.",
    eng: "however",
  },
  { vn: "trăm", pronounce: "/ˈhʌndrəd/", type: "number", eng: "hundred" },
  { vn: "đói", pronounce: "/ˈhʌŋɡri/", type: "adj.", eng: "hungry" },
  { vn: "chồng", pronounce: "/ˈhʌzbənd/", type: "n.", eng: "husband" },
  { vn: "băng, đá", pronounce: "/aɪs/", type: "n.", eng: "ice" },
  { vn: "kem", pronounce: "/aɪs krim/", type: "n.", eng: "ice cream" },
  { vn: "ý tưởng", pronounce: "/aɪˈdiə/", type: "n.", eng: "idea" },
  { vn: "nếu", pronounce: "/ɪf/", type: "conj.", eng: "if" },
  {
    vn: "tưởng tượng",
    pronounce: "/ɪˈmæʤɪn/",
    type: "v.",
    eng: "imagine",
  },
  {
    vn: "quan trọng",
    pronounce: "/ɪmˈpɔrtənt/",
    type: "adj.",
    eng: "important",
  },
  { vn: "cải thiện", pronounce: "/ɪmˈpruv/", type: "v.", eng: "improve" },
  { vn: "trong", pronounce: "/ɪn/", type: "prep., adv.", eng: "in" },
  { vn: "bao gồm", pronounce: "/ɪnˈklud/", type: "v.", eng: "include" },
  {
    vn: "thông tin",
    pronounce: "/ˌɪnfərˈmeɪʃən/",
    type: "n.",
    eng: "information",
  },
  {
    vn: "sự quan tâm, quan tâm",
    pronounce: "/ˈɪntrəst/",
    type: "n., v.",
    eng: "interest",
  },
  {
    vn: "quan tâm",
    pronounce: "/ˈɪntrəstɪd/",
    type: "adj.",
    eng: "interested",
  },
  {
    vn: "thú vị",
    pronounce: "/ˈɪntrəstɪŋ/",
    type: "adj.",
    eng: "interesting",
  },
  {
    vn: "Internet",
    pronounce: "/ˈɪntərˌnɛt/",
    type: "n.",
    eng: "internet",
  },
  {
    vn: "cuộc phỏng vấn, phỏng vấn",
    pronounce: "/ˈɪntərˌvju/",
    type: "n., v.",
    eng: "interview",
  },
  { vn: "vào trong", pronounce: "/ˈɪntu/", type: "prep.", eng: "into" },
  {
    vn: "giới thiệu",
    pronounce: "/ˌɪntrəˈdus/",
    type: "v.",
    eng: "introduce",
  },
  { vn: "đảo", pronounce: "/ˈaɪlənd/", type: "n.", eng: "island" },
  { vn: "nó", pronounce: "/ɪt/", type: "pron.", eng: "it" },
  { vn: "của nó", pronounce: "/ɪts/", type: "det.", eng: "its" },
  { vn: "áo khoác", pronounce: "/ˈjakət/", type: "n.", eng: "jacket" },
  {
    vn: "tháng Một",
    pronounce: "/ˈʤænjuˌɛri/",
    type: "n.",
    eng: "January",
  },
  { vn: "quần jeans", pronounce: "/ʤinz/", type: "n.", eng: "jeans" },
  { vn: "công việc", pronounce: "/ʤɑb/", type: "n.", eng: "job" },
  { vn: "tham gia", pronounce: "/ʤɔɪn/", type: "v.", eng: "join" },
  { vn: "hành trình", pronounce: "/ˈjərnē/", type: "n.", eng: "journey" },
  { vn: "nước ép", pronounce: "/ʤus/", type: "n.", eng: "juice" },
  { vn: "tháng Bảy", pronounce: "/ʤuˈlaɪ/", type: "n.", eng: "July" },
  { vn: "tháng Sáu", pronounce: "/ʤun/", type: "n.", eng: "June" },
  { vn: "chỉ, vừa mới", pronounce: "/ʤʌst/", type: "adv.", eng: "just" },
];

var vocabulary6 = [
  { vn: "giữ", pronounce: "/kip/", type: "v.", eng: "keep" },
  {
    vn: "chìa khóa, chủ chốt",
    pronounce: "/ki/",
    type: "n., adj.",
    eng: "key",
  },
  {
    vn: "kilômét",
    pronounce: "/kɪˈlɑmɪtər/",
    type: "n.",
    eng: "kilometre",
  },
  { vn: "loại", pronounce: "/kaɪnd/", type: "n.", eng: "kind (type)" },
  { vn: "nhà bếp", pronounce: "/ˈkɪʧən/", type: "n.", eng: "kitchen" },
  { vn: "biết", pronounce: "/noʊ/", type: "v.", eng: "know" },
  { vn: "đất, vùng đất", pronounce: "/lænd/", type: "n.", eng: "land" },
  {
    vn: "ngôn ngữ",
    pronounce: "/ˈlæŋɡwɪʤ/",
    type: "n.",
    eng: "language",
  },
  { vn: "lớn", pronounce: "/lɑrʤ/", type: "adj.", eng: "large" },
  {
    vn: "cuối cùng",
    pronounce: "/læst/",
    type: "det.",
    eng: "last (final)",
  },
  { vn: "muộn", pronounce: "/leɪt/", type: "adj., adv.", eng: "late" },
  { vn: "sau", pronounce: "/ˈleɪtər/", type: "adv.", eng: "later" },
  {
    vn: "cười, tiếng cười",
    pronounce: "/læf/",
    type: "v., n.",
    eng: "laugh",
  },
  { vn: "học", pronounce: "/lɜrn/", type: "v.", eng: "learn" },
  { vn: "rời đi", pronounce: "/liv/", type: "v.", eng: "leave" },
  {
    vn: "trái, bên trái, rời khỏi",
    pronounce: "/lɛft/",
    type: "adj., adv., n.",
    eng: "left",
  },
  { vn: "chân", pronounce: "/lɛɡ/", type: "n.", eng: "leg" },
  { vn: "bài học", pronounce: "/ˈlɛsən/", type: "n.", eng: "lesson" },
  { vn: "cho phép", pronounce: "/lɛt/", type: "v.", eng: "let" },
  { vn: "lá thư", pronounce: "/ˈlɛtər/", type: "n.", eng: "letter" },
  {
    vn: "thư viện",
    pronounce: "/ˈlaɪˌbrɛri/",
    type: "n.",
    eng: "library",
  },
  { vn: "nằm", pronounce: "/laɪ/", type: "v.", eng: "lie" },
  { vn: "cuộc sống", pronounce: "/laɪf/", type: "n.", eng: "life" },
  {
    vn: "ánh sáng, nhẹ",
    pronounce: "/laɪt/",
    type: "n., adj.",
    eng: "light (from the sun/a lamp)",
  },
  {
    vn: "thích",
    pronounce: "/laɪk/",
    type: "v.",
    eng: "like (find sb/sth pleasant)",
  },
  { vn: "dòng, đường", pronounce: "/laɪn/", type: "n.", eng: "line" },
  { vn: "sư tử", pronounce: "/ˈlaɪən/", type: "n.", eng: "lion" },
  {
    vn: "danh sách, liệt kê",
    pronounce: "/lɪst/",
    type: "n., v.",
    eng: "list",
  },
  { vn: "lắng nghe", pronounce: "/ˈlɪsən/", type: "v.", eng: "listen" },
  {
    vn: "nhỏ, ít",
    pronounce: "/ˈlɪtəl/",
    type: "adj., det./pron.",
    eng: "little",
  },
  { vn: "sống", pronounce: "/lɪv/", type: "v.", eng: "live" },
  {
    vn: "địa phương",
    pronounce: "/ˈloʊkəl/",
    type: "adj.",
    eng: "local",
  },
  { vn: "dài", pronounce: "/lɔŋ/", type: "adj., adv.", eng: "long" },
  { vn: "nhìn", pronounce: "/lʊk/", type: "v.", eng: "look" },
  { vn: "thua, đánh mất", pronounce: "/luz/", type: "v.", eng: "lose" },
  {
    vn: "nhiều",
    pronounce: "/lɑt/",
    type: "pron., det., adv.",
    eng: "lot",
  },
  {
    vn: "tình yêu, yêu",
    pronounce: "/lʌv/",
    type: "n., v.",
    eng: "love",
  },
  { vn: "bữa trưa", pronounce: "/lʌnʧ/", type: "n.", eng: "lunch" },
  { vn: "máy móc", pronounce: "/məˈʃin/", type: "n.", eng: "machine" },
  {
    vn: "tạp chí",
    pronounce: "/ˈmæɡəˌzin/",
    type: "n.",
    eng: "magazine",
  },
  { vn: "chính", pronounce: "/meɪn/", type: "adj.", eng: "main" },
  { vn: "làm", pronounce: "/meɪk/", type: "v.", eng: "make" },
  { vn: "người đàn ông", pronounce: "/mæn/", type: "n.", eng: "man" },
  { vn: "nhiều", pronounce: "/ˈmɛni/", type: "det./pron.", eng: "many" },
  { vn: "bản đồ", pronounce: "/mæp/", type: "n.", eng: "map" },
  { vn: "tháng Ba", pronounce: "/mɑrʧ/", type: "n.", eng: "March" },
  { vn: "chợ", pronounce: "/ˈmɑrkɪt/", type: "n.", eng: "market" },
  {
    vn: "đã kết hôn",
    pronounce: "/ˈmɛrid/",
    type: "adj.",
    eng: "married",
  },
  {
    vn: "trận đấu, phù hợp",
    pronounce: "/mæʧ/",
    type: "n., v.",
    eng: "match (contest/correspond)",
  },
  { vn: "tháng Năm", pronounce: "/meɪ/", type: "n.", eng: "May" },
  { vn: "có thể", pronounce: "/ˈmeɪbi/", type: "adv.", eng: "maybe" },
  { vn: "tôi (tân ngữ)", pronounce: "/mi/", type: "pron.", eng: "me" },
  { vn: "bữa ăn", pronounce: "/mil/", type: "n.", eng: "meal" },
  { vn: "nghĩa là", pronounce: "/min/", type: "v.", eng: "mean" },
  { vn: "ý nghĩa", pronounce: "/ˈminɪŋ/", type: "n.", eng: "meaning" },
  { vn: "thịt", pronounce: "/mit/", type: "n.", eng: "meat" },
  { vn: "gặp gỡ", pronounce: "/mit/", type: "v.", eng: "meet" },
  { vn: "cuộc họp", pronounce: "/ˈmitɪŋ/", type: "n.", eng: "meeting" },
  { vn: "thành viên", pronounce: "/ˈmɛmbər/", type: "n.", eng: "member" },
  { vn: "thực đơn", pronounce: "/ˈmɛnju/", type: "n.", eng: "menu" },
  { vn: "tin nhắn", pronounce: "/ˈmɛsɪʤ/", type: "n.", eng: "message" },
  { vn: "mét", pronounce: "/ˈmitər/", type: "n.", eng: "metre" },
  {
    vn: "nửa đêm",
    pronounce: "/ˈmɪdˌnaɪt/",
    type: "n.",
    eng: "midnight",
  },
  { vn: "dặm", pronounce: "/maɪl/", type: "n.", eng: "mile" },
  { vn: "sữa", pronounce: "/mɪlk/", type: "n.", eng: "milk" },
  { vn: "triệu", pronounce: "/ˈmɪljən/", type: "number", eng: "million" },
  { vn: "phút", pronounce: "/ˈmɪnət/", type: "n.", eng: "minute" },
  { vn: "nhớ, bỏ lỡ", pronounce: "/mɪs/", type: "v.", eng: "miss" },
  {
    vn: "sai lầm, lỗi",
    pronounce: "/mɪsˈteɪk/",
    type: "n.",
    eng: "mistake",
  },
  {
    vn: "mô hình, người mẫu",
    pronounce: "/ˈmɑdəl/",
    type: "n.",
    eng: "model",
  },
  { vn: "hiện đại", pronounce: "/ˈmɑdərn/", type: "adj.", eng: "modern" },
  {
    vn: "khoảnh khắc",
    pronounce: "/ˈmoʊmənt/",
    type: "n.",
    eng: "moment",
  },
  { vn: "thứ Hai", pronounce: "/ˈmʌnˌdeɪ/", type: "n.", eng: "Monday" },
  { vn: "tiền", pronounce: "/ˈmʌni/", type: "n.", eng: "money" },
  { vn: "tháng", pronounce: "/mʌnθ/", type: "n.", eng: "month" },
  {
    vn: "thêm",
    pronounce: "/mɔr/",
    type: "det./pron., adv.",
    eng: "more",
  },
  { vn: "buổi sáng", pronounce: "/ˈmɔrnɪŋ/", type: "n.", eng: "morning" },
  {
    vn: "hầu hết, nhiều nhất",
    pronounce: "/moʊst/",
    type: "det./pron., adv.",
    eng: "most",
  },
  { vn: "mẹ", pronounce: "/ˈmʌðər/", type: "n.", eng: "mother" },
  { vn: "núi", pronounce: "/ˈmaʊntən/", type: "n.", eng: "mountain" },
  { vn: "con chuột", pronounce: "/maʊs/", type: "n.", eng: "mouse" },
  { vn: "miệng", pronounce: "/maʊθ/", type: "n.", eng: "mouth" },
  { vn: "di chuyển", pronounce: "/muv/", type: "v.", eng: "move" },
  { vn: "phim", pronounce: "/ˈmuvi/", type: "n.", eng: "movie" },
  {
    vn: "nhiều",
    pronounce: "/mʌʧ/",
    type: "det./pron., adv.",
    eng: "much",
  },
  { vn: "mẹ", pronounce: "/mʌm/", type: "n.", eng: "mum" },
  { vn: "bảo tàng", pronounce: "/mjuˈziəm/", type: "n.", eng: "museum" },
  { vn: "âm nhạc", pronounce: "/ˈmjuzɪk/", type: "n.", eng: "music" },
  { vn: "phải", pronounce: "/mʌst/", type: "modal v.", eng: "must" },
  { vn: "của tôi", pronounce: "/maɪ/", type: "det.", eng: "my" },
];
var vocabulary7 = [
  { vn: "tên", pronounce: "/neɪm/", type: "n., v.", eng: "name" },
  {
    vn: "tự nhiên",
    pronounce: "/ˈnæʧərəl/",
    type: "adj.",
    eng: "natural",
  },
  {
    vn: "gần",
    pronounce: "/nɪr/",
    type: "prep., adj., adv.",
    eng: "near",
  },
  { vn: "cần", pronounce: "/nid/", type: "v.", eng: "need" },
  {
    vn: "tiêu cực",
    pronounce: "/ˈnɛɡətɪv/",
    type: "adj.",
    eng: "negative",
  },
  {
    vn: "hàng xóm",
    pronounce: "/ˈneɪbər/",
    type: "n.",
    eng: "neighbour",
  },
  {
    vn: "không bao giờ",
    pronounce: "/ˈnɛvər/",
    type: "adv.",
    eng: "never",
  },
  { vn: "mới", pronounce: "/nu/", type: "adj.", eng: "new" },
  { vn: "tin tức", pronounce: "/nuz/", type: "n.", eng: "news" },
  { vn: "báo", pronounce: "/ˈnuzˌpeɪpər/", type: "n.", eng: "newspaper" },
  {
    vn: "tiếp theo",
    pronounce: "/nɛkst/",
    type: "adj., adv.",
    eng: "next",
  },
  {
    vn: "bên cạnh",
    pronounce: "/nɛkst tu/",
    type: "prep.",
    eng: "next to",
  },
  { vn: "dễ thương, đẹp", pronounce: "/naɪs/", type: "adj.", eng: "nice" },
  { vn: "đêm", pronounce: "/naɪt/", type: "n.", eng: "night" },
  { vn: "chín", pronounce: "/naɪn/", type: "number", eng: "nine" },
  {
    vn: "mười chín",
    pronounce: "/ˈnaɪnˌtin/",
    type: "number",
    eng: "nineteen",
  },
  {
    vn: "chín mươi",
    pronounce: "/ˈnaɪnti/",
    type: "number",
    eng: "ninety",
  },
  { vn: "không", pronounce: "/noʊ/", type: "exclam., det.", eng: "no" },
  {
    vn: "không ai",
    pronounce: "/noʊ wʌn/",
    type: "pron.",
    eng: "no one",
  },
  {
    vn: "không ai",
    pronounce: "/ˈnoʊˌbɑdi/",
    type: "pron.",
    eng: "nobody",
  },
  {
    vn: "phía bắc",
    pronounce: "/nɔrθ/",
    type: "n., adj., adv.",
    eng: "north",
  },
  { vn: "mũi", pronounce: "/noʊz/", type: "n.", eng: "nose" },
  { vn: "không", pronounce: "/nɑt/", type: "adv.", eng: "not" },
  { vn: "ghi chú", pronounce: "/noʊt/", type: "n.", eng: "note" },
  {
    vn: "không có gì",
    pronounce: "/ˈnʌθɪŋ/",
    type: "pron.",
    eng: "nothing",
  },
  {
    vn: "tháng Mười Một",
    pronounce: "/noʊˈvɛmbər/",
    type: "n.",
    eng: "November",
  },
  { vn: "bây giờ", pronounce: "/naʊ/", type: "adv.", eng: "now" },
  { vn: "số", pronounce: "/ˈnʌmbər/", type: "n.", eng: "number" },
  { vn: "y tá", pronounce: "/nɜrs/", type: "n.", eng: "nurse" },
  { vn: "đối tượng", pronounce: "/ˈɑbʤɛkt/", type: "n.", eng: "object" },
  { vn: "giờ", pronounce: "/əˈklɑk/", type: "adv.", eng: "o'clock" },
  {
    vn: "tháng Mười",
    pronounce: "/ɑkˈtoʊbər/",
    type: "n.",
    eng: "October",
  },
  { vn: "của", pronounce: "/ʌv/", type: "prep.", eng: "of" },
  { vn: "tắt, ra", pronounce: "/ɔf/", type: "adv., prep.", eng: "off" },
  { vn: "văn phòng", pronounce: "/ˈɔfɪs/", type: "n.", eng: "office" },
  { vn: "thường", pronounce: "/ˈɔfən/", type: "adv.", eng: "often" },
  { vn: "ôi", pronounce: "/oʊ/", type: "exclam.", eng: "oh" },
  {
    vn: "được",
    pronounce: "/oʊˈkeɪ/",
    type: "exclam., adj./adv.",
    eng: "OK",
  },
  { vn: "cũ, già", pronounce: "/oʊld/", type: "adj.", eng: "old" },
  { vn: "trên, bật", pronounce: "/ɑn/", type: "prep., adv.", eng: "on" },
  { vn: "một lần", pronounce: "/wʌns/", type: "adv.", eng: "once" },
  {
    vn: "một",
    pronounce: "/wʌn/",
    type: "number/det., pron.",
    eng: "one",
  },
  { vn: "củ hành", pronounce: "/ˈʌnjən/", type: "n.", eng: "onion" },
  {
    vn: "trực tuyến",
    pronounce: "/ˈɔnˌlaɪn/",
    type: "adj., adv.",
    eng: "online",
  },
  { vn: "chỉ", pronounce: "/ˈoʊnli/", type: "adj., adv.", eng: "only" },
  { vn: "mở", pronounce: "/ˈoʊpən/", type: "adj., v.", eng: "open" },
  { vn: "ý kiến", pronounce: "/əˈpɪnjən/", type: "n.", eng: "opinion" },
  {
    vn: "đối diện",
    pronounce: "/ˈɑpəzɪt/",
    type: "adj., n., prep., adv.",
    eng: "opposite",
  },
  { vn: "hoặc", pronounce: "/ɔr/", type: "conj.", eng: "or" },
  {
    vn: "quả cam, màu cam",
    pronounce: "/ˈɔrənʤ/",
    type: "n., adj.",
    eng: "orange",
  },
  {
    vn: "đặt hàng, đơn hàng",
    pronounce: "/ˈɔrdər/",
    type: "n., v.",
    eng: "order",
  },
  { vn: "khác", pronounce: "/ˈʌðər/", type: "adj./pron.", eng: "other" },
  { vn: "của chúng tôi", pronounce: "/ˈaʊər/", type: "det.", eng: "our" },
  { vn: "ra ngoài", pronounce: "/aʊt/", type: "adv./prep.", eng: "out" },
  {
    vn: "bên ngoài",
    pronounce: "/ˈaʊtˌsaɪd/",
    type: "adv.",
    eng: "outside",
  },
  {
    vn: "qua, trên, kết thúc",
    pronounce: "/ˈoʊvər/",
    type: "prep., adv.",
    eng: "over",
  },
  { vn: "riêng", pronounce: "/oʊn/", type: "adj./pron.", eng: "own" },
  { vn: "trang", eng: "page", type: "n.", pronounce: "/peɪʤ/" },
  { vn: "sơn, vẽ", eng: "paint", type: "v., n.", pronounce: "/peɪnt/" },
  {
    vn: "bức tranh",
    eng: "painting",
    type: "n.",
    pronounce: "/ˈpeɪntɪŋ/",
  },
  { vn: "đôi", eng: "pair", type: "n.", pronounce: "/pɛr/" },
  { vn: "giấy", eng: "paper", type: "n.", pronounce: "/ˈpeɪpər/" },
  {
    vn: "đoạn văn",
    eng: "paragraph",
    type: "n.",
    pronounce: "/ˈpɛrəˌɡræf/",
  },
  { vn: "cha mẹ", eng: "parent", type: "n.", pronounce: "/ˈpɛrənt/" },
  {
    vn: "công viên, đỗ xe",
    eng: "park",
    type: "n., v.",
    pronounce: "/pɑrk/",
  },
  { vn: "phần", eng: "part", type: "n.", pronounce: "/pɑrt/" },
  {
    vn: "đối tác, cộng sự, bạn đời",
    eng: "partner",
    type: "n.",
    pronounce: "/ˈpɑrtnər/",
  },
  { vn: "bữa tiệc", eng: "party", type: "n.", pronounce: "/ˈpɑrti/" },
  {
    vn: "hộ chiếu",
    eng: "passport",
    type: "n.",
    pronounce: "/ˈpæˌspɔrt/",
  },
  {
    vn: "quá khứ, qua",
    eng: "past",
    type: "adj., n., prep.",
    pronounce: "/pæst/",
  },
  { vn: "trả tiền", eng: "pay", type: "v.", pronounce: "/peɪ/" },
  { vn: "bút", eng: "pen", type: "n.", pronounce: "/pɛn/" },
  { vn: "bút chì", eng: "pencil", type: "n.", pronounce: "/ˈpɛnsəl/" },
  { vn: "người", eng: "people", type: "n.", pronounce: "/ˈpipəl/" },
  { vn: "hạt tiêu", eng: "pepper", type: "n.", pronounce: "/ˈpɛpər/" },
  {
    vn: "hoàn hảo",
    eng: "perfect",
    type: "adj.",
    pronounce: "/ˈpɜrfɪkt/",
  },
  { vn: "giai đoạn", eng: "period", type: "n.", pronounce: "/ˈpɪriəd/" },
  { vn: "người", eng: "person", type: "n.", pronounce: "/ˈpɜrsən/" },
  {
    vn: "cá nhân",
    eng: "personal",
    type: "adj.",
    pronounce: "/ˈpɜrsɪnɪl/",
  },
  {
    vn: "điện thoại, gọi điện thoại",
    eng: "phone",
    type: "n., v.",
    pronounce: "/foʊn/",
  },
  { vn: "bức ảnh", eng: "photo", type: "n.", pronounce: "/ˈfoʊˌtoʊ/" },
  {
    vn: "bức ảnh",
    eng: "photograph",
    type: "n.",
    pronounce: "/ˈfoʊtəˌɡræf/",
  },
  { vn: "cụm từ", eng: "phrase", type: "n.", pronounce: "/freɪz/" },
  { vn: "đàn piano", eng: "piano", type: "n.", pronounce: "/piˈænoʊ/" },
  { vn: "bức tranh", eng: "picture", type: "n.", pronounce: "/ˈpɪkʧər/" },
  { vn: "mảnh, miếng", eng: "piece", type: "n.", pronounce: "/pis/" },
  { vn: "con heo", eng: "pig", type: "n.", pronounce: "/pɪɡ/" },
  { vn: "màu hồng", eng: "pink", type: "adj., n.", pronounce: "/pɪŋk/" },
  { vn: "nơi chốn", eng: "place", type: "n.", pronounce: "/pleɪs/" },
  {
    vn: "kế hoạch, lên kế hoạch",
    eng: "plan",
    type: "n., v.",
    pronounce: "/plæn/",
  },
  { vn: "máy bay", eng: "plane", type: "n.", pronounce: "/pleɪn/" },
  { vn: "cây trồng", eng: "plant", type: "n.", pronounce: "/plænt/" },
  {
    vn: "chơi, vở kịch",
    eng: "play",
    type: "v., n.",
    pronounce: "/pleɪ/",
  },
  { vn: "người chơi", eng: "player", type: "n.", pronounce: "/ˈpleɪər/" },
  { vn: "làm ơn", eng: "please", type: "exclam.", pronounce: "/pliz/" },
  { vn: "điểm", eng: "point", type: "n.", pronounce: "/pɔɪnt/" },
  { vn: "cảnh sát", eng: "police", type: "n.", pronounce: "/pəˈlis/" },
  {
    vn: "cảnh sát (nam)",
    eng: "policeman",
    type: "n.",
    pronounce: "/pəˈlismən/",
  },
  { vn: "bể bơi", eng: "pool", type: "n.", pronounce: "/pul/" },
  { vn: "nghèo", eng: "poor", type: "adj.", pronounce: "/pur/" },
  {
    vn: "phổ biến",
    eng: "popular",
    type: "adj.",
    pronounce: "/ˈpɑpjələr/",
  },
  {
    vn: "tích cực",
    eng: "positive",
    type: "adj.",
    pronounce: "/ˈpɑzətɪv/",
  },
  {
    vn: "khả thi",
    eng: "possible",
    type: "adj.",
    pronounce: "/ˈpɑsəbəl/",
  },
  {
    vn: "bưu kiện, đăng",
    eng: "post",
    type: "n., v.",
    pronounce: "/poʊst/",
  },
  {
    vn: "khoai tây",
    eng: "potato",
    type: "n.",
    pronounce: "/pəˈteɪtoʊ/",
  },
  { vn: "bảng Anh", eng: "pound", type: "n.", pronounce: "/paʊnd/" },
  {
    vn: "luyện tập",
    eng: "practice",
    type: "n.",
    pronounce: "/ˈpræktɪs/",
  },
  {
    vn: "thực hành",
    eng: "practise",
    type: "v.",
    pronounce: "/ˈpræktɪs/",
  },
  { vn: "thích hơn", eng: "prefer", type: "v.", pronounce: "/prɪˈfɜr/" },
  { vn: "chuẩn bị", eng: "prepare", type: "v.", pronounce: "/prɪˈpɛr/" },
  {
    vn: "trình bày, đưa ra; hiện tại, bây giờ, món quà",
    eng: "present",
    type: "adj., n.",
    pronounce: "/ˈprɛzənt/",
  },
  {
    vn: "xinh đẹp, khá",
    eng: "pretty",
    type: "adj., adv.",
    pronounce: "/ˈprɪti/",
  },
  { vn: "giá", eng: "price", type: "n.", pronounce: "/praɪs/" },
  {
    vn: "có lẽ",
    eng: "probably",
    type: "adv.",
    pronounce: "/ˈprɑbəbli/",
  },
  { vn: "vấn đề", eng: "problem", type: "n.", pronounce: "/ˈprɑbləm/" },
  { vn: "sản phẩm", eng: "product", type: "n.", pronounce: "/ˈprɑdʌkt/" },
  {
    vn: "chương trình",
    eng: "programme",
    type: "n.",
    pronounce: "/ˈproʊɡræm/",
  },
  { vn: "dự án", eng: "project", type: "n.", pronounce: "/ˈprɑʤɛkt/" },
  {
    vn: "màu tím",
    eng: "purple",
    type: "adj., n.",
    pronounce: "/ˈpɜrpəl/",
  },
  { vn: "đặt, để", eng: "put", type: "v.", pronounce: "/pʊt/" },
  {
    vn: "một phần tư, 15 phút",
    eng: "quarter",
    type: "n.",
    pronounce: "/ˈkwɔrtər/",
  },
  { vn: "câu hỏi", eng: "question", type: "n.", pronounce: "/ˈkwɛsʧən/" },
  { vn: "nhanh", eng: "quick", type: "adj.", pronounce: "/kwɪk/" },
  {
    vn: "nhanh chóng",
    eng: "quickly",
    type: "adv.",
    pronounce: "/ˈkwɪkli/",
  },
  { vn: "im lặng", eng: "quiet", type: "adj.", pronounce: "/ˈkwaɪət/" },
  { vn: "khá", eng: "quite", type: "adv.", pronounce: "/kwaɪt/:" },
];
var vocabulary8 = [
  {
    vn: "đài phát thanh",
    pronounce: "/ˈreɪdioʊ/",
    type: "n.",
    eng: "radio",
  },
  { vn: "mưa", pronounce: "/reɪn/", type: "n., v.", eng: "rain" },
  { vn: "đọc", pronounce: "/rid/", type: "v.", eng: "read" },
  { vn: "người đọc", pronounce: "/ˈridər/", type: "n.", eng: "reader" },
  { vn: "việc đọc", pronounce: "/ˈridɪŋ/", type: "n.", eng: "reading" },
  { vn: "sẵn sàng", pronounce: "/ˈrɛdi/", type: "adj.", eng: "ready" },
  { vn: "chân thật, thực tế", pronounce: "/riəl/", type: "adj.", eng: "real" },
  { vn: "thật sự", pronounce: "/ˈrɪli/", type: "adv.", eng: "really" },
  { vn: "lý do", pronounce: "/ˈrizən/", type: "n.", eng: "reason" },
  { vn: "đỏ, màu đỏ", pronounce: "/rɛd/", type: "adj., n.", eng: "red" },
  { vn: "thư giãn", pronounce: "/rɪˈlæks/", type: "v.", eng: "relax" },
  { vn: "nhớ", pronounce: "/rɪˈmɛmbər/", type: "v.", eng: "remember" },
  { vn: "lặp lại", pronounce: "/rɪˈpit/", type: "v.", eng: "repeat" },
  { vn: "báo cáo", pronounce: "/rɪˈpɔrt/", type: "n.", eng: "report" },
  {
    vn: "nhà hàng",
    pronounce: "/ˈrɛstəˌrɑnt/",
    type: "n.",
    eng: "restaurant",
  },
  { vn: "kết quả", pronounce: "/rɪˈzʌlt/", type: "n.", eng: "result" },
  {
    vn: "trở lại, sự trở lại",
    pronounce: "/rɪˈtɜrn/",
    type: "v., n.",
    eng: "return",
  },
  { vn: "gạo, cơm", pronounce: "/raɪs/", type: "n.", eng: "rice" },
  { vn: "giàu", pronounce: "/rɪʧ/", type: "adj.", eng: "rich" },
  { vn: "cưỡi, đi (xe)", pronounce: "/raɪd/", type: "v.", eng: "ride" },
  {
    vn: "đúng, phải, bên phải",
    pronounce: "/raɪt/",
    type: "adj., adv., n.",
    eng: "right",
  },
  { vn: "sông", pronounce: "/ˈrɪvər/", type: "n.", eng: "river" },
  { vn: "con đường", pronounce: "/roʊd/", type: "n.", eng: "road" },
  { vn: "phòng", pronounce: "/rum/", type: "n.", eng: "room" },
  {
    vn: "thói quen, công việc hàng ngày",
    pronounce: "/ruˈtin/",
    type: "n.",
    eng: "routine",
  },
  { vn: "quy tắc", pronounce: "/rul/", type: "n.", eng: "rule" },
  { vn: "chạy", pronounce: "/rʌn/", type: "v.", eng: "run" },
  { vn: "buồn", pronounce: "/sæd/", type: "adj.", eng: "sad" },
  { vn: "món salad", pronounce: "/ˈsæləd/", type: "n.", eng: "salad" },
  { vn: "muối", pronounce: "/sɔlt/", type: "n.", eng: "salt" },
  {
    vn: "giống nhau, như nhau",
    pronounce: "/seɪm/",
    type: "adj., pron., adv.",
    eng: "same",
  },
  {
    vn: "bánh sandwich",
    pronounce: "/ˈsændwɪʧ/",
    type: "n.",
    eng: "sandwich",
  },
  {
    vn: "thứ Bảy",
    pronounce: "/ˈsætərˌdeɪ/",
    type: "n.",
    eng: "Saturday",
  },
  { vn: "nói", pronounce: "/seɪ/", type: "v.", eng: "say" },
  { vn: "trường học", pronounce: "/skuːl/", type: "n.", eng: "school" },
  { vn: "khoa học", pronounce: "/ˈsaɪəns/", type: "n.", eng: "science" },
  {
    vn: "nhà khoa học",
    pronounce: "/ˈsaɪəntɪst/",
    type: "n.",
    eng: "scientist",
  },
  { vn: "biển", pronounce: "/siː/", type: "n.", eng: "sea" },
  {
    vn: "thứ hai",
    pronounce: "/ˈsɛkənd/",
    type: "det./number",
    eng: "second (next after the first)",
  },
  {
    vn: "giây",
    pronounce: "/ˈsɛkənd/",
    type: "n.",
    eng: "second (unit of time)",
  },
  { vn: "phần, mục", pronounce: "/ˈsɛkʃən/", type: "n.", eng: "section" },
  { vn: "thấy, nhìn thấy", pronounce: "/siː/", type: "v.", eng: "see" },
  { vn: "bán", pronounce: "/sɛl/", type: "v.", eng: "sell" },
  { vn: "gửi", pronounce: "/sɛnd/", type: "v.", eng: "send" },
  { vn: "câu", pronounce: "/ˈsɛntəns/", type: "n.", eng: "sentence" },
  {
    vn: "tháng Chín",
    pronounce: "/sɛpˈtɛmbər/",
    type: "n.",
    eng: "September",
  },
  { vn: "số bảy", pronounce: "/ˈsɛvən/", type: "number", eng: "seven" },
  {
    vn: "số mười bảy",
    pronounce: "/ˌsɛvənˈtin/",
    type: "number",
    eng: "seventeen",
  },
  {
    vn: "số bảy mươi",
    pronounce: "/ˈsɛvən ti/",
    type: "number",
    eng: "seventy",
  },
  { vn: "chia sẻ", pronounce: "/ʃɛr/", type: "v.", eng: "share" },
  { vn: "cô ấy", pronounce: "/ʃi/", type: "pron.", eng: "she" },
  { vn: "con cừu", pronounce: "/ʃiːp/", type: "n.", eng: "sheep" },
  { vn: "áo sơ mi", pronounce: "/ʃɜrt/", type: "n.", eng: "shirt" },
  { vn: "giày", pronounce: "/ʃuː/", type: "n.", eng: "shoe" },
  {
    vn: "cửa hàng; mua sắm",
    pronounce: "/ʃɑp/",
    type: "n., v.",
    eng: "shop",
  },
  { vn: "mua sắm", pronounce: "/ˈʃɑpɪŋ/", type: "n.", eng: "shopping" },
  { vn: "ngắn", pronounce: "/ʃɔrt/", type: "adj.", eng: "short" },
  { vn: "nên", pronounce: "/ʃʊd/", type: "modal v.", eng: "should" },
  {
    vn: "trình diễn, buổi trình diễn",
    pronounce: "/ʃoʊ/",
    type: "v., n.",
    eng: "show",
  },
  {
    vn: "vòi hoa sen, tắm vòi hoa sen",
    pronounce: "/ˈʃaʊər/",
    type: "n.",
    eng: "shower",
  },
  { vn: "ốm", pronounce: "/sɪk/", type: "adj.", eng: "sick" },
  {
    vn: "tương tự",
    pronounce: "/ˈsɪmɪlər/",
    type: "adj.",
    eng: "similar",
  },
  { vn: "hát", pronounce: "/sɪŋ/", type: "v.", eng: "sing" },
  { vn: "ca sĩ", pronounce: "/ˈsɪŋər/", type: "n.", eng: "singer" },
  { vn: "chị/em gái", pronounce: "/ˈsɪstər/", type: "n.", eng: "sister" },
  { vn: "ngồi", pronounce: "/sɪt/", type: "v.", eng: "sit" },
  {
    vn: "tình huống",
    pronounce: "/ˌsɪtʃuˈeɪʃən/",
    type: "n.",
    eng: "situation",
  },
  { vn: "số sáu", pronounce: "/sɪks/", type: "number", eng: "six" },
  {
    vn: "số mười sáu",
    pronounce: "/ˌsɪksˈtin/",
    type: "number",
    eng: "sixteen",
  },
  {
    vn: "số sáu mươi",
    pronounce: "/ˈsɪksti/",
    type: "number",
    eng: "sixty",
  },
  { vn: "kỹ năng", pronounce: "/skɪl/", type: "n.", eng: "skill" },
  { vn: "váy ngắn", pronounce: "/skɜrt/", type: "n.", eng: "skirt" },
  { vn: "ngủ", pronounce: "/slip/", type: "v.", eng: "sleep" },
  { vn: "chậm", pronounce: "/sloʊ/", type: "adj.", eng: "slow" },
  { vn: "nhỏ", pronounce: "/smɔl/", type: "adj.", eng: "small" },
  { vn: "con rắn", pronounce: "/sneɪk/", type: "n.", eng: "snake" },
  {
    vn: "tuyết; tuyết rơi",
    pronounce: "/snoʊ/",
    type: "n., v.",
    eng: "snow",
  },
  {
    vn: "vì vậy, do đó",
    pronounce: "/soʊ/",
    type: "adv., conj.",
    eng: "so",
  },
  { vn: "một số", pronounce: "/sʌm/", type: "det., pron.", eng: "some" },
  {
    vn: "ai đó",
    pronounce: "/ˈsʌmˌbɑdi/",
    type: "pron.",
    eng: "somebody",
  },
  { vn: "ai đó", pronounce: "/ˈsʌmˌwʌn/", type: "pron.", eng: "someone" },
  {
    vn: "điều gì đó",
    pronounce: "/ˈsʌmˌθɪŋ/",
    type: "pron.",
    eng: "something",
  },
  {
    vn: "thỉnh thoảng, đôi khi",
    pronounce: "/ˈsʌmˌtaɪmz/",
    type: "adv.",
    eng: "sometimes",
  },
  { vn: "con trai", pronounce: "/sʌn/", type: "n.", eng: "son" },
  { vn: "bài hát", pronounce: "/sɔŋ/", type: "n.", eng: "song" },
  { vn: "sớm", pronounce: "/sun/", type: "adv.", eng: "soon" },
  {
    vn: "xin lỗi",
    pronounce: "/ˈsɑri/",
    type: "adj., exclam.",
    eng: "sorry",
  },
  {
    vn: "âm thanh; nghe",
    pronounce: "/saʊnd/",
    type: "n., v.",
    eng: "sound",
  },
  { vn: "súp", pronounce: "/sup/", type: "n.", eng: "soup" },
  {
    vn: "phía nam, hướng nam",
    pronounce: "/saʊθ/",
    type: "n., adj., adv.",
    eng: "south",
  },
  { vn: "không gian", pronounce: "/speɪs/", type: "n.", eng: "space" },
  { vn: "nói", pronounce: "/spik/", type: "v.", eng: "speak" },
  {
    vn: "đặc biệt",
    pronounce: "/ˈspɛʃəl/",
    type: "adj.",
    eng: "special",
  },
  { vn: "đánh vần", pronounce: "/spɛl/", type: "v.", eng: "spell" },
  {
    vn: "sự đánh vần",
    pronounce: "/ˈspɛlɪŋ/",
    type: "n.",
    eng: "spelling",
  },
  {
    vn: "chi tiêu, dành",
    pronounce: "/spɛnd/",
    type: "v.",
    eng: "spend",
  },
  { vn: "thể thao", pronounce: "/spɔrt/", type: "n.", eng: "sport" },
  { vn: "mùa xuân", pronounce: "/sprɪŋ/", type: "n.", eng: "spring" },
  { vn: "đứng", pronounce: "/stænd/", type: "v.", eng: "stand" },
  { vn: "ngôi sao", pronounce: "/stɑr/", type: "n.", eng: "star" },
  { vn: "bắt đầu", pronounce: "/stɑrt/", type: "v.", eng: "start" },
  {
    vn: "lời tuyên bố",
    pronounce: "/ˈsteɪtmənt/",
    type: "n.",
    eng: "statement",
  },
  { vn: "nhà ga", pronounce: "/ˈsteɪʃən/", type: "n.", eng: "station" },
  { vn: "ở lại", pronounce: "/steɪ/", type: "v.", eng: "stay" },
  { vn: "vẫn", pronounce: "/stɪl/", type: "adv.", eng: "still" },
  {
    vn: "dừng lại; điểm dừng",
    pronounce: "/stɑp/",
    type: "v., n.",
    eng: "stop",
  },
  { vn: "câu chuyện", pronounce: "/ˈstɔri/", type: "n.", eng: "story" },
  { vn: "đường phố", pronounce: "/strit/", type: "n.", eng: "street" },
  { vn: "mạnh mẽ", pronounce: "/strɔŋ/", type: "adj.", eng: "strong" },
  {
    vn: "sinh viên",
    pronounce: "/ˈstudənt/",
    type: "n.",
    eng: "student",
  },
  {
    vn: "sự học tập; học",
    pronounce: "/ˈstʌdi/",
    type: "n., v.",
    eng: "study",
  },
  { vn: "phong cách", pronounce: "/staɪl/", type: "n.", eng: "style" },
  {
    vn: "môn học, chủ đề",
    pronounce: "/ˈsʌbʤɪkt/",
    type: "n.",
    eng: "subject",
  },
  {
    vn: "sự thành công",
    pronounce: "/səkˈsɛs/",
    type: "n.",
    eng: "success",
  },
  { vn: "đường", pronounce: "/ˈʃʊgər/", type: "n.", eng: "sugar" },
  { vn: "mùa hè", pronounce: "/ˈsʌmər/", type: "n.", eng: "summer" },
  { vn: "mặt trời", pronounce: "/sʌn/", type: "n.", eng: "sun" },
  { vn: "Chủ Nhật", pronounce: "/ˈsʌndeɪ/", type: "n.", eng: "Sunday" },
  {
    vn: "siêu thị",
    pronounce: "/ˈsupərˌmɑrkɪt/",
    type: "n.",
    eng: "supermFarket",
  },
  { vn: "chắc chắn", pronounce: "/ʃʊr/", type: "adj.", eng: "sure" },
  { vn: "áo len", pronounce: "/ˈswɛtər/", type: "n.", eng: "sweater" },
  { vn: "bơi", pronounce: "/swɪm/", type: "v.", eng: "swim" },
  { vn: "bơi lội", pronounce: "/ˈswɪmɪŋ/", type: "n.", eng: "swimming" },
];
var vocabulary9 = [
  { vn: "cái bàn", pronounce: "/ˈteɪbəl/", type: "n.", eng: "table" },
  { vn: "màng theo, nhận", pronounce: "/teɪk/", type: "v.", eng: "take" },
  { vn: "nói chuyện", pronounce: "/tɔk/", type: "v.", eng: "talk" },
  { vn: "cao", pronounce: "/tɔl/", type: "adj.", eng: "tall" },
  { vn: "xe taxi", pronounce: "/ˈtæksi/", type: "n.", eng: "taxi" },
  { vn: "trà", pronounce: "/ti/", type: "n.", eng: "tea" },
  { vn: "dạy", pronounce: "/tiʧ/", type: "v.", eng: "teach" },
  { vn: "giáo viên", pronounce: "/ˈtiʧər/", type: "n.", eng: "teacher" },
  { vn: "đội", pronounce: "/tim/", type: "n.", eng: "team" },
  {
    vn: "thanh thiếu niên",
    pronounce: "/ˈtinˌeɪʤər/",
    type: "n.",
    eng: "teenager",
  },
  {
    vn: "điện thoại; gọi điện",
    pronounce: "/ˈtɛləˌfoʊn/",
    type: "n., v.",
    eng: "telephone",
  },
  {
    vn: "tivi",
    pronounce: "/ˈtɛləˌvɪʒən/",
    type: "n.",
    eng: "television",
  },
  { vn: "nói", pronounce: "/tɛl/", type: "v.", eng: "tell" },
  { vn: "mười", pronounce: "/tɛn/", type: "number", eng: "ten" },
  { vn: "quần vợt", pronounce: "/ˈtɛnɪs/", type: "n.", eng: "tennis" },
  {
    vn: "khủng khiếp",
    pronounce: "/ˈtɛrəbəl/",
    type: "adj.",
    eng: "terrible",
  },
  {
    vn: "bài kiểm tra; kiểm tra",
    pronounce: "/tɛst/",
    type: "n., v.",
    eng: "test",
  },
  { vn: "văn bản", pronounce: "/tɛkst/", type: "n.", eng: "text" },
  { vn: "hơn", pronounce: "/ðæn/", type: "conj.", eng: "than" },
  { vn: "cảm ơn", pronounce: "/θæŋk/", type: "v.", eng: "thank" },
  {
    vn: "cảm ơn",
    pronounce: "/θæŋks/",
    type: "exclam., n.",
    eng: "thanks",
  },
  { vn: "nhà hát", pronounce: "/ˈθiətər/", type: "n.", eng: "theatre" },
  { vn: "sau đó", pronounce: "/ðɛn/", type: "adv.", eng: "then" },
  { vn: "ở đó", pronounce: "/ðɛr/", type: "adv.", eng: "there" },
  { vn: "điều, vật", pronounce: "/θɪŋ/", type: "n.", eng: "thing" },
  { vn: "nghĩ", pronounce: "/θɪŋk/", type: "v.", eng: "think" },
  { vn: "thứ ba", pronounce: "/θɜrd/", type: "number", eng: "third" },
  {
    vn: "khát nước",
    pronounce: "/ˈθɜrsti/",
    type: "adj.",
    eng: "thirsty",
  },
  {
    vn: "mười ba",
    pronounce: "/ˈθɜrˈtin/",
    type: "number",
    eng: "thirteen",
  },
  { vn: "ba mươi", pronounce: "/ˈθɜrti/", type: "number", eng: "thirty" },
  {
    vn: "một nghìn",
    pronounce: "/ˈθaʊzənd/",
    type: "number",
    eng: "thousand",
  },
  { vn: "ba", pronounce: "/θri/", type: "number", eng: "three" },
  {
    vn: "qua, xuyên qua",
    pronounce: "/θru/",
    type: "prep., adv.",
    eng: "through",
  },
  { vn: "Thứ Năm", pronounce: "/ˈθɜrzdeɪ/", type: "n.", eng: "Thursday" },
  { vn: "vé", pronounce: "/ˈtɪkɪt/", type: "n.", eng: "ticket" },
  { vn: "thời gian", pronounce: "/taɪm/", type: "n.", eng: "time" },
  { vn: "mệt mỏi", pronounce: "/ˈtaɪərd/", type: "adj.", eng: "tired" },
  { vn: "tiêu đề", pronounce: "/ˈtaɪtəl/", type: "n.", eng: "title" },
  {
    vn: "đến, để",
    pronounce: "/tu/",
    type: "prep., infinitive marker",
    eng: "to",
  },
  {
    vn: "hôm nay",
    pronounce: "/təˈdeɪ/",
    type: "adv., n.",
    eng: "today",
  },
  {
    vn: "cùng nhau",
    pronounce: "/təˈgɛðər/",
    type: "adv.",
    eng: "together",
  },
  {
    vn: "nhà vệ sinh",
    pronounce: "/ˈtɔɪlət/",
    type: "n.",
    eng: "toilet",
  },
  { vn: "cà chua", pronounce: "/təˈmeɪtoʊ/", type: "n.", eng: "tomato" },
  {
    vn: "ngày mai",
    pronounce: "/təˈmɑːroʊ/",
    type: "adv., n.",
    eng: "tomorrow",
  },
  {
    vn: "tối nay",
    pronounce: "/təˈnaɪt/",
    type: "adv., n.",
    eng: "tonight",
  },
  { vn: "cũng", pronounce: "/tuː/", type: "adv.", eng: "too" },
  { vn: "răng", pronounce: "/tuːθ/", type: "n.", eng: "tooth" },
  { vn: "chủ đề", pronounce: "/ˈtɑːpɪk/", type: "n.", eng: "topic" },
  {
    vn: "khách du lịch",
    pronounce: "/ˈtʊrɪst/",
    type: "n.",
    eng: "tourist",
  },
  { vn: "thị trấn", pronounce: "/taʊn/", type: "n.", eng: "town" },
  {
    vn: "giao thông, lưu lượng",
    pronounce: "/ˈtræfɪk/",
    type: "n.",
    eng: "traffic",
  },
  { vn: "tàu hỏa", pronounce: "/treɪn/", type: "n.", eng: "train" },
  {
    vn: "đi du lịch, chuyến du lịch",
    pronounce: "/ˈtrævəl/",
    type: "v., n.",
    eng: "travel",
  },
  { vn: "cây", pronounce: "/triː/", type: "n.", eng: "tree" },
  { vn: "chuyến đi", pronounce: "/trɪp/", type: "n.", eng: "trip" },
  {
    vn: "quần dài",
    pronounce: "/ˈtraʊzərz/",
    type: "n.",
    eng: "trousers",
  },
  { vn: "đúng", pronounce: "/truː/", type: "adj.", eng: "true" },
  { vn: "thử", pronounce: "/traɪ/", type: "v.", eng: "try" },
  { vn: "áo thun", pronounce: "/ˈtiːʃɜːrt/", type: "n.", eng: "T-shirt" },
  { vn: "thứ Ba", pronounce: "/ˈtjuːzdeɪ/", type: "n.", eng: "Tuesday" },
  { vn: "rẽ, lượt", pronounce: "/tɜːrn/", type: "v., n.", eng: "Turn" },
  { vn: "ti vi", pronounce: "/ˌtiːˈviː/", type: "n.", eng: "TV" },
  { vn: "mười hai", pronounce: "/twɛlv/", type: "number", eng: "Twelve" },
  {
    vn: "hai mươi",
    pronounce: "/ˈtwɛnti/",
    type: "number",
    eng: "Twenty",
  },
  { vn: "hai lần", pronounce: "/twaɪs/", type: "adv.", eng: "Twice" },
  { vn: "hai", pronounce: "/tuː/", type: "number", eng: "Two" },
  { vn: "loại", pronounce: "/taɪp/", type: "n.", eng: "Type" },
  { vn: "cái ô", pronounce: "/ʌmˈbrɛlə/", type: "n.", eng: "Umbrella" },
  {
    vn: "chú, cậu, bác",
    pronounce: "/ˈʌŋkəl/",
    type: "n.",
    eng: "Uncle",
  },
  {
    vn: "dưới",
    pronounce: "/ˈʌndər/",
    type: "prep., adv.",
    eng: "Under",
  },
  {
    vn: "hiểu",
    pronounce: "/ˌʌndərˈstænd/",
    type: "v.",
    eng: "Understand",
  },
  {
    vn: "trường đại học",
    pronounce: "/ˌjuːnɪˈvɜːrsɪti/",
    type: "n.",
    eng: "University",
  },
  {
    vn: "cho đến khi",
    pronounce: "/ənˈtɪl/",
    type: "conj., prep.",
    eng: "Until",
  },
  { vn: "lên", pronounce: "/ʌp/", type: "adv., prep.", eng: "Up" },
  {
    vn: "lên tầng trên",
    pronounce: "/ˌʌpˈstɛərz/",
    type: "adv.",
    eng: "Upstairs",
  },
  { vn: "chúng tôi", pronounce: "/ʌs/", type: "pron.", eng: "Us" },
  { vn: "sử dụng", pronounce: "/juːz/", type: "v.", eng: "Use" },
  { vn: "hữu ích", pronounce: "/ˈjuːsfəl/", type: "adj.", eng: "Useful" },
  {
    vn: "thường xuyên",
    pronounce: "/ˈjuːʒuəli/",
    type: "adv.",
    eng: "Usually",
  },
  {
    vn: "kỳ nghỉ",
    pronounce: "/veɪˈkeɪʃən/",
    type: "n.",
    eng: "Vacation",
  },
  {
    vn: "rau củ",
    pronounce: "/ˈvɛdʒtəbl/",
    type: "n.",
    eng: "Vegetable",
  },
  { vn: "rất", pronounce: "/ˈvɛri/", type: "adv.", eng: "Very" },
  { vn: "video", pronounce: "/ˈvɪdioʊ/", type: "n.", eng: "Video" },
  { vn: "làng", pronounce: "/ˈvɪlɪdʒ/", type: "n.", eng: "Village" },
  {
    vn: "thăm, chuyến thăm",
    pronounce: "/ˈvɪzɪt/",
    type: "v., n.",
    eng: "Visit",
  },
  {
    vn: "khách thăm",
    pronounce: "/ˈvɪzɪtər/",
    type: "n.",
    eng: "Visitor",
  },
  { vn: "chờ", pronounce: "/weɪt/", type: "v.", eng: "Wait" },
  {
    vn: "bồi bàn nam",
    pronounce: "/ˈweɪtər/",
    type: "n.",
    eng: "Waiter",
  },
  { vn: "thức dậy", pronounce: "/weɪk/", type: "v.", eng: "Wake" },
  {
    vn: "đi bộ, cuộc đi bộ",
    pronounce: "/wɔːk/",
    type: "v., n.",
    eng: "Walk",
  },
  { vn: "tường", pronounce: "/wɔːl/", type: "n.", eng: "Wall" },
  { vn: "muốn", pronounce: "/wɑːnt/", type: "v.", eng: "Want" },
  { vn: "ấm áp", pronounce: "/wɔːrm/", type: "adj.", eng: "Warm" },
  { vn: "rửa", pronounce: "/wɑːʃ/", type: "v.", eng: "Wash" },
  {
    vn: "xem, đồng hồ",
    pronounce: "/wɑːtʃ/",
    type: "v., n.",
    eng: "Watch",
  },
  { vn: "nước", pronounce: "/ˈwɔːtər/", type: "n.", eng: "Water" },
  { vn: "đường", pronounce: "/weɪ/", type: "n.", eng: "Way" },
  { vn: "chúng tôi", pronounce: "/wiː/", type: "pron.", eng: "We" },
  { vn: "mặc, đeo", pronounce: "/wɛər/", type: "v.", eng: "Wear" },
  { vn: "thời tiết", pronounce: "/ˈwɛðər/", type: "n.", eng: "Weather" },
  {
    vn: "trang web",
    pronounce: "/ˈwɛbsaɪt/",
    type: "n.",
    eng: "Website",
  },
  { vn: "thứ Tư", pronounce: "/ˈwɛnzdeɪ/", type: "n.", eng: "Wednesday" },
  { vn: "tuần", pronounce: "/wiːk/", type: "n.", eng: "Week" },
  {
    vn: "cuối tuần",
    pronounce: "/ˈwiːkɛnd/",
    type: "n.",
    eng: "Weekend",
  },
  {
    vn: "chào mừng, đón chào",
    pronounce: "/ˈwɛlkəm/",
    type: "exclam., v., adj.",
    eng: "Welcome",
  },
  {
    vn: "tốt, khỏe, được",
    pronounce: "/wɛl/",
    type: "adv., adj., exclam.",
    eng: "Well",
  },
  {
    vn: "phía Tây",
    pronounce: "/wɛst/",
    type: "n., adj., adv.",
    eng: "West",
  },
  { vn: "cái gì", pronounce: "/wɒt/", type: "pron./det.", eng: "What" },
  {
    vn: "khi nào",
    pronounce: "/wɛn/",
    type: "adv., pron., conj.",
    eng: "When",
  },
  { vn: "ở đâu", pronounce: "/wɛər/", type: "adv., conj.", eng: "Where" },
  { vn: "nào", pronounce: "/wɪtʃ/", type: "pron./det.", eng: "Which" },
  {
    vn: "màu trắng",
    pronounce: "/waɪt/",
    type: "adj., n.",
    eng: "White",
  },
  { vn: "ai", pronounce: "/huː/", type: "pron.", eng: "Who" },
  { vn: "tại sao", pronounce: "/waɪ/", type: "adv.", eng: "Why" },
  { vn: "vợ", pronounce: "/waɪf/", type: "n.", eng: "Wife" },
  { vn: "sẽ", pronounce: "/wɪl/", type: "modal v.", eng: "Will" },
  { vn: "thắng", pronounce: "/wɪn/", type: "v.", eng: "Win" },
  { vn: "cửa sổ", pronounce: "/ˈwɪndoʊ/", type: "n.", eng: "Window" },
  { vn: "rượu vang", pronounce: "/waɪn/", type: "n.", eng: "Wine" },
  { vn: "mùa đông", pronounce: "/ˈwɪntər/", type: "n.", eng: "Winter" },
  { vn: "với", pronounce: "/wɪð/", type: "prep.", eng: "With" },
  {
    vn: "không có",
    pronounce: "/wɪˈðaʊt/",
    type: "prep.",
    eng: "Without",
  },
  { vn: "phụ nữ", pronounce: "/ˈwʊmən/", type: "n.", eng: "Woman" },
  {
    vn: "tuyệt vời",
    pronounce: "/ˈwʌndərfəl/",
    type: "adj.",
    eng: "Wonderful",
  },
  { vn: "từ", pronounce: "/wɜːrd/", type: "n.", eng: "Word" },
  { vn: "làm việc", pronounce: "/wɜːrk/", type: "v., n.", eng: "Work" },
  {
    vn: "người lao động",
    pronounce: "/ˈwɜːrkər/",
    type: "n.",
    eng: "Worker",
  },
  { vn: "thế giới", pronounce: "/wɜːrld/", type: "n.", eng: "World" },
  { vn: "sẽ", pronounce: "/wʊd/", type: "modal v.", eng: "Would" },
  { vn: "viết", pronounce: "/raɪt/", type: "v.", eng: "Write" },
  { vn: "nhà văn", pronounce: "/ˈraɪtər/", type: "n.", eng: "Writer" },
  {
    vn: "việc viết lách",
    pronounce: "/ˈraɪtɪŋ/",
    type: "n.",
    eng: "Writing",
  },
  { vn: "sai", pronounce: "/rɒŋ/", type: "adj., adv.", eng: "Wrong" },
  { vn: "ừ", pronounce: "/jɛə/", type: "exclam.", eng: "Yeah" },
  { vn: "năm", pronounce: "/jɪər/", type: "n.", eng: "Year" },
  {
    vn: "màu vàng",
    pronounce: "/ˈjɛloʊ/",
    type: "adj., n.",
    eng: "Yellow",
  },
  { vn: "vâng", pronounce: "/jɛs/", type: "exclam., n.", eng: "Yes" },
  {
    vn: "hôm qua",
    pronounce: "/ˈjɛstərdeɪ/",
    type: "n.",
    eng: "Yesterday",
  },
  { vn: "bạn", pronounce: "/juː/", type: "pron.", eng: "You" },
  { vn: "trẻ", pronounce: "/jʌŋ/", type: "adj.", eng: "Young" },
  { vn: "của bạn", pronounce: "/jʊər/", type: "det.", eng: "Your" },
  {
    vn: "bản thân bạn",
    pronounce: "/jɔːrˈsɛlf/",
    type: "pron.",
    eng: "Yourself",
  },
];
// var vocabulary10 = [
//   {
//     vn: "khả năng",
//     pronounce: "/ˌəˈbɪləti/",
//     type: "n.",
//     eng: "ability",
//   },
//   {
//     vn: "có khả năng",
//     pronounce: "/ˈeɪbl̩/",
//     type: "adj.",
//     eng: "able",
//   },
//   {
//     vn: "ở nước ngoài",
//     pronounce: "/əˈbrɔːd/",
//     type: "adv.",
//     eng: "abroad",
//   },
//   {
//     vn: "chấp nhận",
//     pronounce: "/əkˈsept/",
//     type: "v.",
//     eng: "accept",
//   },
//   {
//     vn: "tai nạn",
//     pronounce: "/ˈæksɪdənt/",
//     type: "n.",
//     eng: "accident",
//   },
//   {
//     vn: "theo như",
//     pronounce: "/əˈkɔːrdɪŋ tuː/",
//     type: "prep.",
//     eng: "according to",
//   },
//   {
//     vn: "đạt được",
//     pronounce: "/əˈtʃiːv/",
//     type: "v.",
//     eng: "achieve",
//   },
//   {
//     vn: "tích cực, hoạt động",
//     pronounce: "/ˈæktɪv/",
//     type: "adj.",
//     eng: "active",
//   },
//   { vn: "hành động", pronounce: "/ækt/", type: "v.", eng: "act" },
//   {
//     vn: "thực ra",
//     pronounce: "/ˈæktʃuəli/",
//     type: "adv.",
//     eng: "actually",
//   },
//   {
//     vn: "ưu điểm",
//     pronounce: "/ədˈvæntɪdʒ/",
//     type: "n.",
//     eng: "advantage",
//   },
//   {
//     vn: "cuộc phiêu lưu",
//     pronounce: "/ədˈventʃər/",
//     type: "n.",
//     eng: "adventure",
//   },
//   {
//     vn: "quảng cáo",
//     pronounce: "/ˈædvərtaɪz/",
//     type: "v.",
//     eng: "advertise",
//   },
//   {
//     vn: "quảng cáo",
//     pronounce: "/ˌæd.vɚˈtaɪz.mənt/",
//     type: "n.",
//     eng: "advertisement",
//   },
//   {
//     vn: "sự quảng cáo",
//     pronounce: "/ˈædvərtaɪzɪŋ/",
//     type: "n.",
//     eng: "advertising",
//   },
//   {
//     vn: "ảnh hưởng đến",
//     pronounce: "/əˈfekt/",
//     type: "v.",
//     eng: "affect",
//   },
//   {
//     vn: "chống lại",
//     pronounce: "/əˈɡenst/",
//     type: "prep.",
//     eng: "against",
//   },
//   {
//     vn: "hãng hàng không",
//     pronounce: "/ˈɛəlaɪn/",
//     type: "n.",
//     eng: "airline",
//   },
//   {
//     vn: "gần như",
//     pronounce: "/ˈɔːlmoʊst/",
//     type: "adv.",
//     eng: "almost",
//   },
//   { vn: "sống", pronounce: "/əˈlaɪv/", type: "adj.", eng: "alive" },
//   {
//     vn: "một mình",
//     pronounce: "/əˈloʊn/",
//     type: "adj./adv.",
//     eng: "alone",
//   },
//   { vn: "cho phép", pronounce: "/əˈlaʊ/", type: "v.", eng: "allow" },
//   { vn: "đã", pronounce: "/ɔːlˈrɛdi/", type: "adv.", eng: "already" },
//   {
//     vn: "dọc theo",
//     pronounce: "/əˈlɔːŋ/",
//     type: "prep., adv.",
//     eng: "along",
//   },
//   {
//     vn: "phương án thay thế",
//     pronounce: "/ɔːlˈtɜːrnətɪv/",
//     type: "n.",
//     eng: "alternative",
//   },
//   {
//     vn: "mặc dù",
//     pronounce: "/ɔːlˈðoʊ/",
//     type: "conj.",
//     eng: "although",
//   },
//   {
//     vn: "trong số",
//     pronounce: "/əˈmʌŋ/",
//     type: "prep.",
//     eng: "among",
//   },
//   {
//     vn: "số lượng",
//     pronounce: "/əˈmaʊnt/",
//     type: "n.",
//     eng: "amount",
//   },
//   {
//     vn: "cổ xưa",
//     pronounce: "/ˈeɪnʃənt/",
//     type: "adj.",
//     eng: "ancient",
//   },
//   {
//     vn: "mắt cá chân",
//     pronounce: "/ˈæŋkl̩/",
//     type: "n.",
//     eng: "ankle",
//   },
//   { vn: "tất cả", pronounce: "/ɔːl/", type: "adv.", eng: "all" },

//   {
//     vn: "không còn nữa",
//     pronounce: "/ˈɛni mɔːr/",
//     type: "adv.",
//     eng: "any more",
//   },
//   {
//     vn: "dù sao đi nữa",
//     pronounce: "/ˈɛniweɪ/",
//     type: "adv.",
//     eng: "anyway",
//   },
//   {
//     vn: "bất kỳ đâu",
//     pronounce: "/ˈɛniwer/",
//     type: "adv.",
//     eng: "anywhere",
//   },
//   {
//     vn: "xuất hiện",
//     pronounce: "/əˈpɪr/",
//     type: "v.",
//     eng: "appear",
//   },
//   {
//     vn: "sự xuất hiện",
//     pronounce: "/əˈpɪrəns/",
//     type: "n.",
//     eng: "appearance",
//   },
//   { vn: "áp dụng", pronounce: "/əˈplaɪ/", type: "v.", eng: "apply" },
//   {
//     vn: "kiến trúc",
//     pronounce: "/ˈɑːrkɪtektʃər/",
//     type: "n.",
//     eng: "architecture",
//   },
//   {
//     vn: "kiến trúc sư",
//     pronounce: "/ˈɑːrkɪtekt/",
//     type: "n.",
//     eng: "architect",
//   },
//   {
//     vn: "tranh luận",
//     pronounce: "/ˈɑːrɡjuː/",
//     type: "v.",
//     eng: "argue",
//   },
//   {
//     vn: "cuộc tranh luận",
//     pronounce: "/dəˈbāt/",
//     type: "n.",
//     eng: "debate",
//   },
//   { vn: "quân đội", pronounce: "/ˈɑːrmi/", type: "n.", eng: "army" },
//   {
//     vn: "sắp xếp",
//     pronounce: "/əˈreɪndʒ/",
//     type: "v.",
//     eng: "arrange",
//   },
//   {
//     vn: "sự sắp xếp",
//     pronounce: "/əˈreɪndʒmənt/",
//     type: "n.",
//     eng: "arrangement",
//   },

//   { vn: "ngủ", pronounce: "/əˈsliːp/", type: "adj.", eng: "asleep" },
//   {
//     vn: "trợ lý",
//     pronounce: "/əˈsɪstənt/",
//     type: "n., adj.",
//     eng: "assistant",
//   },
//   {
//     vn: "vận động viên",
//     pronounce: "/ˈæθliːt/",
//     type: "n.",
//     eng: "athlete",
//   },
//   {
//     vn: "tấn công",
//     pronounce: "/əˈtæk/",
//     type: "n., v.",
//     eng: "attack",
//   },
//   { vn: "tham dự", pronounce: "/əˈtɛnd/", type: "v.", eng: "attend" },
//   {
//     vn: "sự chú ý",
//     pronounce: "/əˈtɛnʃən/",
//     type: "n., exclam.",
//     eng: "attention",
//   },
//   {
//     vn: "hấp dẫn",
//     pronounce: "/əˈtræktɪv/",
//     type: "adj.",
//     eng: "attractive",
//   },
//   {
//     vn: "khán giả",
//     pronounce: "/ˈɔːdiəns/",
//     type: "n.",
//     eng: "audience",
//   },
//   { vn: "tác giả", pronounce: "/ˈɔːθər/", type: "n.", eng: "author" },
//   {
//     vn: "có sẵn",
//     pronounce: "/əˈveɪləbl̩/",
//     type: "adj.",
//     eng: "available",
//   },
//   {
//     vn: "trung bình",
//     pronounce: "/ˈævərɪdʒ/",
//     type: "adj., n.",
//     eng: "average",
//   },
//   { vn: "tránh", pronounce: "/əˈvɔɪd/", type: "v.", eng: "avoid" },
//   {
//     vn: "giải thưởng",
//     pronounce: "/əˈwɔːrd/",
//     type: "n.",
//     eng: "award",
//   },
//   {
//     vn: "kinh khủng",
//     pronounce: "/ˈɔːfl̩/",
//     type: "adj.",
//     eng: "awful",
//   },
// ];

// const vocabulary11 = [
//   {
//     vn: "nền, bối cảnh",
//     pronounce: "/ˈbækˌɡraʊnd/",
//     type: "n.",
//     eng: "background",
//   },
//   { vn: "một cách tồi tệ", pronounce: "/ˈbædli/", type: "adv.", eng: "badly" },
//   { vn: "bóng chày", pronounce: "/ˈbeɪsbɔːl/", type: "n.", eng: "baseball" },
//   { vn: "dựa vào", pronounce: "/beɪst/", type: "adj.", eng: "based" },
//   { vn: "bóng rổ", pronounce: "/ˈbæskɪtbɔːl/", type: "n.", eng: "basketball" },
//   { vn: "tiết tấu", pronounce: "/biːt/", type: "v.", eng: "beat" },
//   { vn: "thịt bò", pronounce: "/biːf/", type: "n.", eng: "beef" },
//   { vn: "cư xử", pronounce: "/bɪˈheɪv/", type: "v.", eng: "behave" },
//   { vn: "hành vi", pronounce: "/bɪˈheɪvjər/", type: "n.", eng: "behaviour" },
//   { vn: "thuộc về", pronounce: "/bɪˈlɔːŋ/", type: "v.", eng: "belong" },
//   { vn: "thắt lưng", pronounce: "/bɛlt/", type: "n.", eng: "belt" },
//   { vn: "lợi ích", pronounce: "/ˈbɛnɪfɪt/", type: "n.", eng: "benefit" },
//   { vn: "tỷ", pronounce: "/ˈbɪljən/", type: "number", eng: "billion" },
//   { vn: "thùng rác", pronounce: "/bɪn/", type: "n.", eng: "bin" },
//   { vn: "sinh học", pronounce: "/baɪˈɑːlədʒi/", type: "n.", eng: "biology" },
//   { vn: "sự ra đời", pronounce: "/bɜːrθ/", type: "n.", eng: "birth" },
//   { vn: "bánh quy", pronounce: "/ˈbɪskɪt/", type: "n.", eng: "biscuit" },
//   { vn: "một chút", pronounce: "/bɪt/", type: "n.", eng: "bit" },
//   { vn: "trống rỗng", pronounce: "/blæŋk/", type: "adj., n.", eng: "blank" },
//   { vn: "máu", pronounce: "/blʌd/", type: "n.", eng: "blood" },
//   { vn: "thổi", pronounce: "/bloʊ/", type: "v.", eng: "blow" },
//   { vn: "bảng, tấm", pronounce: "/bɔːrd/", type: "n.", eng: "board" },
//   { vn: "đun sôi", pronounce: "/bɔɪl/", type: "v.", eng: "boil" },
//   { vn: "xương", pronounce: "/boʊn/", type: "n.", eng: "bone" },
//   { vn: "đặt chỗ, đặt trước", pronounce: "/bʊk/", type: "v.", eng: "book" },
//   { vn: "mượn", pronounce: "/ˈbɑːroʊ/", type: "v.", eng: "borrow" },
//   { vn: "sếp", pronounce: "/bɔːs/", type: "n.", eng: "boss" },
//   { vn: "đáy", pronounce: "/ˈbɑːtəm/", type: "n., adj.", eng: "bottom" },
//   { vn: "tô", pronounce: "/boʊl/", type: "n.", eng: "bowl" },
//   { vn: "não", pronounce: "/breɪn/", type: "n.", eng: "brain" },
//   { vn: "cầu", pronounce: "/brɪdʒ/", type: "n.", eng: "bridge" },
//   { vn: "sáng, rực rỡ", pronounce: "/braɪt/", type: "adj.", eng: "bright" },
//   {
//     vn: "xuất sắc, tuyệt vời",
//     pronounce: "/ˈbrɪljənt/",
//     type: "adj.",
//     eng: "brilliant",
//   },
//   { vn: "bị hỏng, vỡ", pronounce: "/ˈbroʊkən/", type: "adj.", eng: "broken" },
//   { vn: "chải, cọ", pronounce: "/brʌʃ/", type: "v., n.", eng: "brush" },
//   { vn: "đốt cháy", pronounce: "/bɜːrn/", type: "v.", eng: "burn" },
//   {
//     vn: "doanh nhân",
//     pronounce: "/ˈbɪznɪsmæn/",
//     type: "n.",
//     eng: "businessman",
//   },
// ];
export const vocabulary = [
  ...vocabulary1,
  ...vocabulary2,
  ...vocabulary3,
  ...vocabulary4,
  ...vocabulary5,
  ...vocabulary6,
  ...vocabulary7,
  ...vocabulary8,
  ...vocabulary9,
  // ...vocabulary10,
  // ...vocabulary11,
];